### ISSUE TITLE
Dead code in navbar.js

### ISSUE THREAD

**Issue by Laogeodritt** [Sylhare/Type-on-Strap#100]
In navbar.js, there is some code registered to the resize event to restore a visible menu when the window width increases beyond 320px.

However, all visibility and transition animations is handled in pure CSS now, and the action taken by the code does nothing (no context, to my knowledge, where an inline style is applied to the menu element). This seems to be dead code left in as an oversight and should be removed:

```js
    /*
    * Display the navbar back to normal after resize
    */
    window.addEventListener('resize', function() {
        var w = window.innerWidth;
        if (w > 320) {
            menu.removeAttribute('style');
        }
    });
```

**Comment by Sylhare** [comment]
Thanks I will fix that ;)
