### ISSUE TITLE
For tags containing spaces, anchor links in tags_list.html are incorrect + invalid HTML

### ISSUE THREAD

**Issue by Laogeodritt** [Sylhare/Type-on-Strap#101]
In [tags_list.html](https://github.com/Sylhare/Type-on-Strap/blob/dev/_includes/tags_list.html), the tag anchor link doesn't correspond to the anchors on the tag page, for tags containing spaces. Additionally, the generated links are invalid HTML (spaces not allowed in `href` attribute).

The cgi_escape filter should be used, as is done for the anchor IDs on the tag page.

Line 13:

```
    <a class="button" href="{{site.baseurl}}/tags#{{tag}}">
```

should be:

```
    <a class="button" href="{{site.baseurl}}/tags#{{ tag | cgi_escape }}">
```

(Pardon the lack of pull req, my website setup is horribly ad hoc right now and not set up with a clone of this repo. This issue is simple enough that hopefully it shouldn't be much of a problem either way =P )

**Comment by Sylhare** [comment]
@Laogeodritt 
It should be all fixed.
Thanks for all of those bug finding, it is of a huge help! 😁

**Comment by Laogeodritt** [comment]
Cheers, glad to help!
