### ISSUE TITLE
Allow opt-out of Disqus comments per page

### ISSUE THREAD

**Issue by CookiePLMonster** [Sylhare/Type-on-Strap#102]
Do you think it's a good idea? I noticed comments show up in my portfolio pages, which is... not very useful.

Unless perhaps portfolio pages using a `post` layout is an error? That's how you have them on your page, at least - but I feel like `page` layout makes more sense.

EDIT:
I migrated my portfolio pages from type `post` to `page` and IMO it works better for those - just doesn't show a date. Oh well, can customize it better via `subtitle` anyway!

**Comment by Sylhare** [comment]
Oh yes indeed, I think at first it was meant to be a page. Because I putt it in the page folder.
Let me update that 😉
