### ISSUE TITLE
How to create page in navbar with link to blog post overview?

### ISSUE THREAD

**Issue by jjuppe** [Sylhare/Type-on-Strap#104]
Hi 
thanks a lot @Sylhare for this super easy to setup website. 
I am currently trying to add another page called "Blog" to the navbar. So I created a new blog.md file and wrote:

layout: home
title: Blog
permalink: /blog/

into the file. 
The tab appears in the navbar but the blogs (like on the home screen) are not shown. What do I have to do to also see the blog posts?

Thanks,
Janis

**Comment by Sylhare** [comment]
Hi @jjuppe 

As I understood you want to create a home page different from the home page called blog and display the blog post from `_posts` inside of it, right?
Do you have a picture, or a link to the repository so I can try it?

**Comment by jjuppe** [comment]
Yes, exactly. I like that when I open my github pages website, the blog posts from '_posts' are directly shown.  However, if I am currently on the "About" page and want to return to the blog post list then I would have to click on the upper left corner (name or icon of blog), right? 

My idea is to add a new page to the navbar that is called "Blog" where I see the exact same list as on the home page. In my opinion it is just more intuitive to get back to the blog lists like this again.

![Blog in navbar](https://user-images.githubusercontent.com/6388453/44159727-9b9d3d00-a0b8-11e8-8c8f-771df6da0fb6.png)

Sorry for abusing the issues section like this but I appreciate your help.
You can find my current code under: https://github.com/jjuppe/jjuppe.github.io

**Comment by Sylhare** [comment]
Hi, 

Then instead of creating a new page, why don't you just add a title to the `index.html` so it appears in the navbar?
It should work this way  😉

**Comment by Sylhare** [comment]
Indeed it messes with the paginator which uses the "home" url to paginate the pages. By putting into another page, you change the url so the page can't display the blog paginated anymore.

I am closing this one then :wink:
