### ISSUE TITLE
Can we fix or change  the order of pages in navigation bar?

### ISSUE THREAD

**Issue by Shubhanshu07** [Sylhare/Type-on-Strap#105]

**Comment by Sylhare** [comment]
Hi, the order is set based on alphabetical order, there are no way to set it implemented.

**Comment by Shubhanshu07** [comment]
But I am on getting the alphabetical order. I have added **Team** page in the navigation bar and its coming first.

**Comment by Sylhare** [comment]
Ok, let me do some test, it might be the order set in the folder from where you generate the file then.

**Comment by Sylhare** [comment]
Hi!

The search page and the tag page will always be at the end (the little icones).
Page order is determined by the page `filename` which is different from the `title`.

So if you want a team page, create a `team.md` in the `_page` folder and it will be automatically ordered alphabetically with the other files of that folder.
Let me know if you have any trouble doing that.

Here is what you can put at the top of your team page as a reference:
```
--- 
layout: page
title : Team
permalink: /team/
subtitle: "This is my team" 
feature-img: "assets/img/pexels/computer.jpeg"
tags: [Archive]
---
```

**Comment by Shubhanshu07** [comment]
Thanks for your help. Now it is coming in alphabetical order.

**Comment by Sylhare** [comment]
Good 😉

**Comment by LindyBalboa** [comment]
I just had to figure this out as well. Although not recommended, I suppose one could set the order by hacking the file names e.g. A_team.md, B_resources.md, C_blog.md.
