### ISSUE TITLE
Dynamic typing with typed.js.

### ISSUE THREAD

**Issue by akhan4u** [sylhare/Type-on-Strap#107]
Hi, firstly thanks for the theme. I like it's miminal design. Can you implement dynamic typing using typed.js on to this theme. Please let me know, I'll provide you with references.

**Comment by Sylhare** [comment]
Hi, I do not know typed.js 

I you have some reference of what it does and what you mean by implement, I'd be interested to take a look ;)

**Comment by akhan4u** [comment]
Yes sure. The typed.js is a JavaScript Typing Animation Library. 
https://github.com/mattboldt/typed.js/

This looks like kinda cool. This is a live hosted example of the same. 
https://mattboldt.com/demos/typed-js/

I have also seen some similar stuff on this jekyll theme (See the README,md for the screenshots)
https://github.com/le4ker/personal-jekyll-theme

I was wondering if this can be implemented on the header sector; like we get this dynamically typed text between the image. 

Let me know if you need to know more.

**Comment by Sylhare** [comment]
Oh ok, I see. That's kinda gadget 😅
The implementation seems to be using some jquery (that we would need to change because we want a jquery free theme):
```
$(".intro-text").typed({
      strings: myQuotes,
      typeSpeed: {{ site.type-speed }},
      backDelay: {{ site.delete-delay }},
      startDelay: {{ site.start-delay }},
      loop: {{ site..loop }},
      loopCount: {{ site.loop-count }},
      cursorChar: "|"
    });
```
Then there are some parameters to be added to the config file. Then I guess we would need to add some html with some css `intro-text` class that will have the typed.js behaviour.
Let me think about it, if I have some leeway during the next month I'll do some test 😉

**Comment by akhan4u** [comment]
Sure, Yeah some variables like type-speed, delete-delay, start-delay to our _config.yml. And yes some CSS Styling along with html. Let me know when you will be able to make it. I will be interested to know in this regard. :+1: :heart:

**Comment by sylhare** [comment]
Hi, so I don't think I really want to add some fancy javascript. 
However if you want to add it you can do replace in `home.html`:

```html
---
layout: default
---
<!-- typed.js library -->
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.9"></script>
<div class="home">
  {% if site.theme_settings.header_text %}
  <div id="main" class="call-out"
  style="background-image: url('{{ site.theme_settings.header_feature_image | relative_url }}')">
    <h1 class="typed-title"> {{ site.theme_settings.header_text }} </h1>
  </div>
  {% endif %}

  {% include blog.html %}
    
</div>
<script>
var options = {
  strings: ["", "{{ site.theme_settings.header_text }}"],
  typeSpeed: 50
}

var typed = new Typed(".typed-title", options);
</script>

```

And it should work as desired. 😉
