### ISSUE TITLE
How do I create a new image folder under assets/img/ for new content ?

### ISSUE THREAD

**Issue by NanditaDamaraju** [Sylhare/Type-on-Strap#108]
I am trying to add a new folder in the assets/img/ folder to add more content. But everytime I run jekyll serve, it gets deleted. How should I go about this ?

**Comment by Sylhare** [comment]
Hi!

So you create a folder like `assets/img/new_folder` inside of whitch you put images? 
And then when you refer to those images in your blog post, they aren't created?
Can you provide some example?

I'll look into it,

Thanks

**Comment by NanditaDamaraju** [comment]
That seemed to be happening due to a network issue on my end. Thanks for the help!

**Comment by Sylhare** [comment]
Ok 😉closing now.
