### ISSUE TITLE
links not working within posts on homepage

### ISSUE THREAD

**Issue by patrickmroskam** [Sylhare/Type-on-Strap#110]
when creating a link within a post the link does not show up on the home page where multiple posts are shown. It does however work on the individual post page. Is this a config thing I am missing or is this not possible? This is my first time with Jekyll and markdown so I am still getting adjusted.

**Comment by CookiePLMonster** [comment]
Yes, this is a design choice. Take a look at `_layouts\home.html`:

`{{ post.excerpt | strip_html | escape }}`

**Comment by patrickmroskam** [comment]
Thank you so much for pointing me to the right place!
