### ISSUE TITLE
Search for Portfolio entries is bugged

### ISSUE THREAD

**Issue by CookiePLMonster** [Sylhare/Type-on-Strap#111]
Something I noticed on my website and I just noticed your base website is affected too. Not quite sure how to fix it, so I'm posting an issue instead.

Basically, Search functionality is semi-broken for Portfolio (and possibly any other containers which are not a `_post` container) containers. You cannot search for them by site content and searching by site title shows an incorrect excerpt.

Take this Portfolio entry for example: https://sylhare.github.io/Type-on-Strap/portfolio/ninja
Navigate to Search and try to find parts of the first sentence from this page:
> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium

Result:
![image](https://user-images.githubusercontent.com/7947461/44994645-da2f6480-af9f-11e8-9950-a7e373a8860f.png)

Search for title ("Ninja") instead and you get a result, albeit glitched:
![image](https://user-images.githubusercontent.com/7947461/44994656-eca99e00-af9f-11e8-8652-e510ba688a4e.png)

It doesn't seem to be affected by the layout Portfolio entry has - your entries use `post` layout and my entries use `page` layout - yet result is the same.

**Comment by Sylhare** [comment]
Indeed might be something with the search.json that does not get compiled correctly. I think it would require an update of the plugin, or maybe work around with the options.

**Comment by Sylhare** [comment]
It was just a typo in search.json, should be all good now.

**Comment by CookiePLMonster** [comment]
Works perfectly, thanks for a timely fix!

Just update your gh-pages so results are visible straight away :)
