### ISSUE TITLE
Incosistent header font sizes

### ISSUE THREAD

**Issue by CookiePLMonster** [sylhare/Type-on-Strap#113]
Something very minor I'll fix on my page soon, but figured it makes sense to bring it to your attention.

Don't you think font sizes on headers are a bit incosistent? Comparing the text on main page:
https://sylhare.github.io/Type-on-Strap/

and even a subtitle on Portfolio/About (in this case, "Projects I am working on" and not "Portfolio"):
https://sylhare.github.io/Type-on-Strap/portfolio/

the latter is significantly bigger. IMO it'd look better if the sizes were consistent, and thus if main page had the header in same style as sub-titles in other pages.

**Comment by sylhare** [comment]
Oups sorry here, I read your message but never answered.
Well to tell the truth the difference never bothered me. To me the main one was some kind of header for information and summary and the other one was more for a title.

But I can look into it, it could make sense to make it consistent ;)
I think there was some css for the text in the presentation to fit in smaller screen, I would need to take another look into it.
