### ISSUE TITLE
How to use a light theme for Syntax highlighting?

### ISSUE THREAD

**Issue by monirulalom** [sylhare/Type-on-Strap#118]
I am finding a way to set a light theme for syntax highlighting. How to use a light theme for Syntax highlighting ?

**Comment by sylhare** [comment]
Hi,

It uses [base16](http://chriskempson.com/projects/base16/), you can modify the base to put a light theme in the [syntax.css](https://github.com/sylhare/Type-on-Strap/blob/master/_sass/external/_syntax.scss) file.

You can have a list of theme in [Chriskempson/base16](https://github.com/chriskempson/base16#template-repositories) repository ;)
