### ISSUE TITLE
Question: Github send me "potential security vulnerability" 

### ISSUE THREAD

**Issue by noweaver** [sylhare/Type-on-Strap#119]
I didn't know that. Github sends the following message through email to me. How do I fix it? 

https://github.com/guhnguk/dt/network/dependencies#assets%252Fpackage-lock.json

> We fo found a potential security vulnerability in one of your dependencies.
> A dependency defined in assets/package-lock.json has known security vulnerabilities and should be updated.
> 
> Only the owner of this repository can see this message.
> Learn more about vulnerability alerts

**Comment by sylhare** [comment]
Yes that's for gulp which is a nice javascript tool to automate part of your workflow working with a jekyll website (for images, and to minimize images). 

There are no security vulnerability with the theme though. I need to correct the problematic package of used by one of gulp dependencies that's about it.

**Comment by CookiePLMonster** [comment]
> There are no security vulnerability with the theme though.

And even if there was, when using on GitHub it wouldn't be on you to fix it - unless somebody deploys a prebuilt site in case they use an unsupported plugin or something.

**Comment by sylhare** [comment]
I had some difficulties with the transition from gulp 3.9.1 to 4.0.0:

- `['img', 'css']` had to be replace by gulp.series for exemple
- And for `Did you forget to signal async completion?` I had to return something at the end of my gulp tasks to avoid the error.
- Used `node ./node_modules/gulp/bin/gulp.js` to troubleshoot and added some name to the function as well
- Removed the deprecated gulp-utils.

I guess that's good for now.

Sources:
https://www.liquidlight.co.uk/blog/article/how-do-i-update-to-gulp-4/
https://codeburst.io/switching-to-gulp-4-0-271ae63530c0
https://stackoverflow.com/questions/36897877/gulp-error-the-following-tasks-did-not-complete-did-you-forget-to-signal-async/36899424
