### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by farlee2121** [sylhare/Type-on-Strap#120]
Is any desire to move to bootstrap 4? After a brief look around the code, it doesn't look like it would be too hard to upgrade. 

I may be naive though. Are there known roadblocks?

**Comment by farlee2121** [comment]
I replaced the bootstrap version in my copy. It took me a bit to understand the bootstrap usage, but it was trivial to update once I did.

I am impressed by your modular and extensible design!

**Comment by sylhare** [comment]
Hi!
Thanks for the input. 😄  
Now that bootstrap v4 has been released, we could add it to the theme (Is there anything in bootstrap 4 that might break something from the previous version?)

Do you want to make a pull request for bootstrap v4? Let me know.

**Comment by farlee2121** [comment]
I'll pull together a preq here soon

**Comment by farlee2121** [comment]
I submitted the preq. For record purposes, I'm moving the preq comment here.


There is a slight snag with popper (the popover library). It defaults to placing popovers on the body, but the bootstrap styling is scoped only to the page layout.

Unless the user sets the popover container to '.bootstrap-iso' or a child element, the popover will be unstyled.

Do we want to make the poppers be in scope by default?
Some ideas
1. move bootstrap-iso to body
2. query for popper elements and set their container

**Comment by sylhare** [comment]
Well I don't have plans for poppers, we will see with what gets requested.
I will close for now since the branch has been merged ;)
