### ISSUE TITLE
Katex Inline Indicator: How to change it from "$$" to "$"?

### ISSUE THREAD

**Issue by jordytrilaksono** [sylhare/Type-on-Strap#122]
First of all, thank you for this great theme.

I'm currently having problem with your Katex inline indicator and I wish you can help me. How can I change Katex inline indicator to "$" instead of "$$"? I'm using markdown-preview-enhanced (MPE) on atom as markdown previewer and its default inline indicator is "$". I want to make your theme and MPE to work with same rules.

Best regards,

**Comment by sylhare** [comment]
Hi!

It might be a [katex](https://github.com/Khan/KaTeX) issue, I'll look into it to see if there's a parameter I can toggle for that.

**Comment by jordytrilaksono** [comment]
Sorry where I can find that?

**Comment by sylhare** [comment]
Well as of now it is not implemented using auto render, I put that for reference. 
It seems to be possible but I have not succeeded in making it work. Maybe it has to do with `kramdown` using `mathjax` for `$$` equations.

If you want to see where it's implemented, check `katex_init.js`

**Comment by jordytrilaksono** [comment]
Thank you very much

**Comment by sylhare** [comment]
Hi I haven;t figure out how to do this one. I guess you could use a script to convert all of your `$` into `$$`. If at some point I come across the solution I will let you know. I will close it for now.
Sorry.
