### ISSUE TITLE
Hyperlink in navbar

### ISSUE THREAD

**Issue by datduyng** [sylhare/Type-on-Strap#144]
Hello How do I add hyperlink on my navbar?  Creating new `md` file would create a new section on the navbar but i am not sure how to create a hyperlink from there. For example, I would like to add a section that would link back to my blog page(refer to image below)

![hyperlink](https://user-images.githubusercontent.com/35666615/54732575-8a427480-4b62-11e9-8c87-4e3ec6f7222f.PNG)

**Comment by sylhare** [comment]
Hi,

Did you look at "How to create page in navbar with link to blog post overview?" issue #104 ?
I think it might answer what you are trying to do.

If not let me know 😉

**Comment by datduyng** [comment]
Got it Thanks so much!
