### ISSUE TITLE
Installation problem using bundle v2.01

### ISSUE THREAD

**Issue by l-Aeden-l** [sylhare/Type-on-Strap#145]
$ bundle install
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.12) x64-mingw32

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.12)' in any of the relevant sources:
  the local ruby installation

**Comment by sylhare** [comment]
Hi,
Thanks for trying the theme. 

From what you post it seems like the bundler version is not the same.

Maybe you can be a bit more verbose on what solution you tried, which system you are on and what you would like to achieve.
Otherwise it will be difficult to help you.

Thanks

**Comment by l-Aeden-l** [comment]
I already tried to update gem and bundle, nothing works.
I know nothing about how Ruby is working and I don't plane to learn it entirely just to get your system. Jekyll is supposed to facilitate the installation and the using of a website/blog, and even if you propose some interesting features, it makes difficult to keep Jekyll simple because of your system requirement.

**Comment by sylhare** [comment]
If you want to use the theme simply, you can create your own l-Aeden-l .github.io repository while cloning this one.
Then github will automatically generate the page using jekyll.

If you want to make custom modification or want to host the theme, then I guess you would need to make sure you have a basic understanding of how gems and jekyll works and avoid frustration

Here it was saying that your version of bundle was superior to the one in the gemspec. I have updated it, hopefully it will help. 😃
