### ISSUE TITLE
special_page suggestion

### ISSUE THREAD

**Issue by mhagnumdw** [sylhare/Type-on-Strap#148]
Hi!

Would not it be simpler to set a page as special in the page metadata?

Thus avoiding the `special_page` section in the `_config.yml`.

I thought about this when trying to add a `title` html attribute to `<a` in [navbar.html](https://github.com/sylhare/Type-on-Strap/blob/460a487d54ac86426604ff29dbb0cd3907b3f2aa/_includes/navbar.html#L47) getting from page metadata, but at that point I do not have them available.

**Comment by sylhare** [comment]
Allo,

The special pages are special because they are defined with an icon instead of text.
If you want to add another page to the navbar, you can just add it in the `pages` folder.

Or perhaps I misunderstood what you wanted to do, I am always open to new enhancements 😃

**Comment by mhagnumdw** [comment]
Hi!
Maybe I did not explain myself well :smiley: 

For example: how can I add the `title` attribute to the `a` tag [here](https://github.com/sylhare/Type-on-Strap/blob/460a487d54ac86426604ff29dbb0cd3907b3f2aa/_includes/navbar.html#L47)?
Getting the `title` value from [tags.html](https://github.com/sylhare/Type-on-Strap/blob/460a487d54ac86426604ff29dbb0cd3907b3f2aa/pages/tags.html#L3) and [search.html](https://github.com/sylhare/Type-on-Strap/blob/460a487d54ac86426604ff29dbb0cd3907b3f2aa/pages/search.html#L3).

**Comment by sylhare** [comment]
Oh you mean like having the icon and the title of the page?

Like for example:
> tags 🏷 
Instead of 
> 🏷 

Well you could try by adding `{{ page.title }}` inside of the `<a> </a>` as it is done for normal pages and it should work.

**Comment by mhagnumdw** [comment]
No no... :))

I talking about this:
![Peek 2019-05-23 12-35](https://user-images.githubusercontent.com/17688846/58266263-b68f9280-7d57-11e9-8faa-db3b9cb9e5d5.gif)

**Comment by sylhare** [comment]
Oh! ok I get it! I think its name is the `aria-label`.

That's interesting I thought it would appear for both text of icon. Ok so I agree with you, the `aria-label` should be displaying for everything and should come from the `page.title`.

Let me look into it.

**Comment by mhagnumdw** [comment]
> Oh! ok I get it! I think its name is the aria-label.

Sorry!

Note: In the above animation the title appears when the mouse is over the icon because I put the `title` tag in`<a`, see image below:
![image](https://user-images.githubusercontent.com/17688846/58279132-fb292700-7d73-11e9-8cae-2b13380f9b3a.png)

**Comment by sylhare** [comment]
Ah ok, ok! So it's not yet a bug 😛 

So from your suggestion, we should add `title`? I think that's a good idea.
Also I want to look into removing special page and add an `icon` option in the page.

**Comment by mhagnumdw** [comment]
:smiley: 

> So from your suggestion, we should add `title`? I think that's a good idea.

Yes!! And should come from the page.title

> Also I want to look into removing special page and add an icon option in the page instead of in config

Good!

**Comment by sylhare** [comment]
Ok I messed up a bit with the commit and issue number, but the feature should be here!

Now you don't need special page no more:
  - Add `icon: fa-search` if you want an icon (here the loop font awesome icon) in the page.
  - title has been added with the `page.title`
  - Less liquid to generate the same thing and is simpler to use 👌
