### ISSUE TITLE
Right edge of Next button disappears

### ISSUE THREAD

**Issue by mhagnumdw** [sylhare/Type-on-Strap#150]
![Peek 2019-05-23 13-29](https://user-images.githubusercontent.com/17688846/58270029-3a994880-7d5f-11e9-811a-50d58aa5a226.gif)

**Comment by sylhare** [comment]
Hi Thanks so much for reporting the bugs. I am surprised for this one, it did not show on my browser.
Which one are you using?

**Comment by mhagnumdw** [comment]
Hi!

SO: Fedora 28
Browser: Chrome 73.0.3683.103 (Official Build) (64-bit)

Animation down showing the screen resolution (Chrome):
![Peek 2019-05-23 16-13](https://user-images.githubusercontent.com/17688846/58279994-1b59e580-7d76-11e9-8e55-c5b4a5830233.gif)

Note: Firefox 61.0.2 (64-bit) no problem.

**Comment by sylhare** [comment]
Ah I see why I missed it, I use Firefox for dev.

**Comment by kaleid-liner** [comment]
This bug happens on chrome when `width >= 769`. It seems the right fa-icon will overlap the right edge of the button. I use `span` to enclose the content of button as a workaround. I mean:
```html
<span>
     {{ site.theme_settings.str_next_page }}
     <i class="fa fa-chevron-right"></i>
</span>
```

**Comment by sylhare** [comment]
Thanks! That will help me troubleshoot and find a fix.

**Comment by sylhare** [comment]
It should be all good now. The issue was because of the css of the `.button`:

```css
display: inline-block;
```

Basically `inline-block` takes the whole component while the `inline` was considering only the text it seemed in some browser. If you still have the issue let me know.
