### ISSUE TITLE
Improve jekyll build speed

### ISSUE THREAD

**Issue by sylhare** [sylhare/Type-on-Strap#153]
After building the site locally repetitively, I found it quite slow to build to I looked online what could have been the cause of that:

- https://forestry.io/blog/how-i-reduced-my-jekyll-build-time-by-61/ 
- https://carlosbecker.com/posts/jekyll-build-time/ 
- https://blog.webjeda.com/jekyll-build-speed/

Using this to see the time cost per page:

```bash
jekyll serve --profile
```

The goal is to find what is slowing everything down.

**Comment by sylhare** [comment]
Also, to reduce even more, if you have a lot of images you could use as well:

```yaml
keep_files: ["assets/img", "assets/fonts"]
```

**Comment by mhagnumdw** [comment]
Another thing ... I had slowness problem due to the `assets/node_modules`.  It was brutally slow!

So I recommend adding `"**/node_modules"` in the `exclude` attribute in the `_config.yml`. 

What do you think?

**Comment by mhagnumdw** [comment]
Oh, sorry, I just saw that you've already added `"assets/node_modules"`
