### ISSUE TITLE
Suggestion/Idea: author avatar

### ISSUE THREAD

**Issue by mhagnumdw** [sylhare/Type-on-Strap#154]
Hi!

What do you think of the post having the `author_avatar` attribute so it can be displayed in the post listing and in the post itself?

Like this:
![image](https://user-images.githubusercontent.com/17688846/58371159-5f1f2d00-7ee5-11e9-9d72-e19a78c9fb62.png)

I'm not good at design! 😄 

For the future: when clicking on the author direct to a page containing all the posts of the author.

**Comment by sylhare** [comment]
That could be interesting in a multi-author environment.
I like the design 😃 , it could be link to one's github nickname and avatar?

I guess that's worth a try, let me know how you've implemented it, I am thinking either making it by default or maybe as a new feature that you can enable in the `_config`? Would you like to open a pull request for it?

**Comment by mhagnumdw** [comment]
Hi!

> it could be link to one's github nickname and avatar?

Yes! Link to GitHub or anywhere else. This link would be defined in the _front matter_ of the post?

---
For now I've only implemented the author's avatar view without any link. You can see the diff [here](https://github.com/sylhare/Type-on-Strap/compare/master...mhagnumdw:post-info).

I did not create the PR because I think it's just a start and needs a good evaluation of it. You can take the changes and continue.

Let me know about anything!

Print:
![image](https://user-images.githubusercontent.com/17688846/58374563-c6a1a080-7f16-11e9-9295-694c5747724b.png)

**Comment by sylhare** [comment]
I was thinking of adding the `author` field as well in config file. 
For example if you like the feature but you are the sole author in your blog and don't want to bother updating all of your blog post.

I would need to play with it and see how I like it. Thanks a lot for sharing!

**Comment by mhagnumdw** [comment]
One more idea: to have a unique place to define the authors and in the post just put the author ID. I think this avoids duplicating information.

**Comment by mhagnumdw** [comment]
> One more idea: to have a unique place to define the authors and in the post just put the author ID. I think this avoids duplicating information.

Below some prints of my site (code):

In _front matter_ only the ID of the author
![image](https://user-images.githubusercontent.com/17688846/58434182-c2998e00-8090-11e9-8587-84e85dd33b3b.png)

In `_config.yml` the authors definition
![image](https://user-images.githubusercontent.com/17688846/58434218-efe63c00-8090-11e9-9799-be5af4ee7817.png)

In `post_info.html` the author information is retrieved
![image](https://user-images.githubusercontent.com/17688846/58434247-17d59f80-8091-11e9-8ac7-ca0e9b4b5d1a.png)

**Comment by sylhare** [comment]
Looks nice, and if you don't set any author it remains the same look as before?
I'd like to try it myself and see how it looks. Let me know if you wanna submit a PR 😉

**Comment by mhagnumdw** [comment]
> Looks nice, and if you don't set any author it remains the same look as before?

In my case I assume that there is always an author. But I can change this behavior...

> I'd like to try it myself and see it. Let me know if you wanna submit a PR

I'll do it.

:v:

**Comment by sylhare** [comment]
Awesome job @mhagnumdw ! #161 has been merged, I updated the left padding, so that when or without author it is aligned on the left (without border).
I think we can close this one 😉

**Comment by mhagnumdw** [comment]
Nice! I hope to help where possible.
