### ISSUE TITLE
Document how to minimize css, js and images

### ISSUE THREAD

**Issue by mhagnumdw** [sylhare/Type-on-Strap#156]
Add step-by-step in README.md.

```shell
cd assets/
sudo npm install gulp-cli -g
npm install
# then run to minimize
gulp default
```
Also inform that all tasks can be seen in the `gulpfile.js` file.

_ps: I thought about creating this issue because not everyone is familiar with it._

**Comment by sylhare** [comment]
Oh True, good idea 😅 

Can I re-use that for the documentation?
I guess I could add some more steps, like you'd need to have also `node` installed.

**Comment by mhagnumdw** [comment]
Let me handle then. I can do a PR.

**Comment by sylhare** [comment]
Oh nice thanks ;)
