### ISSUE TITLE
Feed description

### ISSUE THREAD

**Issue by mhagnumdw** [sylhare/Type-on-Strap#158]
In `feed.xml` the `<description>` of `<channel>` point to `site.theme_settings.description`, but this attribute does not exist in the `_config.yml` file.

Should it point to `site.description`?

**Comment by sylhare** [comment]
Indeed, good catch 😉

**Comment by mhagnumdw** [comment]
I have already made this change, just need to create the PR.

And `<channel><title>` should I leave as is or point to `site.title`?

**Comment by sylhare** [comment]
I was actually thinking of removing the `title` in `theme_settings` since it was already available in `site.title` but I wanted to check first where it was used.
So yes, I think it is better to point toward `site.title` directly

**Comment by mhagnumdw** [comment]
Cool, I agree!
