### ISSUE TITLE
Change favicon location

### ISSUE THREAD

**Issue by mhagnumdw** [sylhare/Type-on-Strap#162]
Some readers stubbornly seek the favicon from the root of site rather than what is defined in the `<head>` metadata.

What do you think of moving `favicon.ico` to the root of the project?

It's just a very small detail.

**Comment by sylhare** [comment]
Hmm, nah I think it is fine where it is, I don;t recall many people asking for it 😅 
Like when looking at the config file you can get the address. 

I will let it there for the theme, however anybody can feel free to add the favicon and put it anywhere they would want as long as they update the config file.

**Comment by mhagnumdw** [comment]
I agree! Tks!!
