### ISSUE TITLE
Nested Menu

### ISSUE THREAD

**Issue by DavidSchirduan** [sylhare/Type-on-Strap#168]
I'm attempting to add sub-menus to the nav bar, but any nested `<ul>` just show alongside.

I thought I could use some of the nice bootstrap CSS templates for menus, but enabling the bootstrap frontmatter doesn't seem to apply it to the navbar.

Any idea on a better way to handle this?

**Comment by sylhare** [comment]
Allo, 

As of now the bootstrap is only applied to the content of the post.
I have not tested with the navbar, but I am sure it can be done, but you would need to rework the navigation bar, I would start with:

- Enabling bootstrap
- Add the `.bootstrap-iso` class to the correct navbar composent (so it will be formatted the bootstrap way like in the `post.html` layout)
- Add the corresponding bootstrap class to get the layout that you want.

Let me know how that works for you 😉

**Comment by DavidSchirduan** [comment]
I fiddled with it for a while, but the bootstrap elements I'm using were just being fiddly; I think CSS was clashing or something.

I think I'm just going to start from scratch and keep it simpler, rather than wrestling with bootstrap.

Thank you so much for your prompt answer! I am loving this theme; it's fantastic!

**Comment by sylhare** [comment]
Thanks 😄 sorry for the bootstrap issue
