### ISSUE TITLE
Can't deploy to Netlify

### ISSUE THREAD

**Issue by phquiste** [sylhare/Type-on-Strap#172]
I know it isn't actually related to github, but it still is the theme. I love how it looks and would like to use it on netlify, but I can't deploy it correctly, despite it working on github pages.

My code is on https://github.com/phquiste/Type-on-Strap. I already added the gem they ask for here (https://www.netlify.com/blog/2017/05/11/migrating-your-jekyll-site-to-netlify/), so it should be working, but it isn't.

When I connect my repo to Netlify, the deploy stops with this error on the console:
`9:29:20 PM: Bundler could not find compatible versions for gem "jekyll":
9:29:20 PM:   In Gemfile:
9:29:20 PM:     github-pages was resolved to 4, which depends on
9:29:20 PM:       jekyll (= 1.1.2)
9:29:20 PM:     type-on-strap was resolved to 1.3.0, which depends on
9:29:20 PM:       jekyll (~> 3.8, >= 3.8.5)
9:29:20 PM: Bundler could not find compatible versions for gem "jekyll-seo-tag":
9:29:20 PM:   In Gemfile:
9:29:20 PM:     github-pages was resolved to 198, which depends on
9:29:20 PM:       jekyll-seo-tag (= 2.5.0)
9:29:20 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
9:29:20 PM:     type-on-strap was resolved to 1.3.0, which depends on
9:29:20 PM:       jekyll-seo-tag (~> 2.6)
9:29:20 PM: Bundler could not find compatible versions for gem "rouge":
9:29:20 PM:   In Gemfile:
9:29:20 PM:     github-pages was resolved to 198, which depends on
9:29:20 PM:       rouge (= 2.2.1)
9:29:20 PM:     github-pages was resolved to 198, which depends on
9:29:20 PM:       jekyll (= 3.8.5) was resolved to 3.8.5, which depends on
9:29:20 PM:         rouge (>= 1.7, < 4)
9:29:20 PM: Error during gem install`

For better visualization of the error, here is a printscreen: https://i.imgur.com/xNPJG34.png

What can it be? Really appreciate any kind of answer and congrats on this great theme.

**Comment by sylhare** [comment]
Hi, 

Which gem did you put? It might be that the gem is outdated. 

I have little knowledge about Netlify. I will try with it and see if I try the installation as well. I will let you know if I succeed.

**Comment by sylhare** [comment]
Ok,

So I have tried and it worked without any issues.

First I linked my account and Netlifty, then I used github as my repository. As it is mentioned in the website you provided.

However and I think here is the tricky part which might explain why it failed I used `bundle exec jekyll build` and `_site`:

![netlifty](https://user-images.githubusercontent.com/20642750/61802196-0f35e700-adfe-11e9-8291-0114048b9662.png)

However I don't see where you had to provide a gem. To check the deploy settings you can go on `Deploys > Deploy settings > Build & Deploy > Edit Settings`.

You can check my own personal blog on netlifty (which uses Type-on-Strap: [https://boring-austin-e592d5.netlify.com/](https://boring-austin-e592d5.netlify.com/) )
