### ISSUE TITLE
What is the use of 'url' option in site configuration 

### ISSUE THREAD

**Issue by yuehaowang** [sylhare/Type-on-Strap#176]
I referred to the [documentation in README](https://github.com/sylhare/Type-on-Strap#configure-type-on-strap). There is an option named 'url' which I can not find in [jekyll's options](https://jekyllrb.com/docs/configuration/options/). I tried to remove it and I found my site can still work without any difference.

I wonder whether the 'url' option is required in this theme and how it take effects.

**Comment by sylhare** [comment]
Allo,

The `url` is simply the url which the jekyll will be served at once built. When run locally for dev it will be accessible via `localhost`. 
You can have a loot at it in the [jekyll configuration options](https://jekyllrb.com/docs/variables/) at the name `site.url`
