### ISSUE TITLE
Image capture & changing the portfolio "search" icon to the post titles. 

### ISSUE THREAD

**Issue by senemp** [sylhare/Type-on-Strap#177]
Hi again,

1. For the image capture issue, I was thinking something like this -- please see the right corner: 
<img width="1669" alt="62424693-f7ead980-b6da-11e9-8299-c62c5ea12016" src="https://user-images.githubusercontent.com/15858372/62462751-d9471a00-b790-11e9-9aa3-cff0dec75d7b.png">
(Again, I would like to be able to add captions to the "feature-img" if it's possible) 

2. How can I change the search icon that appears in the portfolio section? I want to use the title of my posts as captures instead of an icon. When I erase this (<i class="fa fa-search-plus fa-3x"></i>) from portfolio.html I can make the icon disappear but I don't know how to replace it with the post titles.

Thank you for your help -- I appreciate it.

**Comment by sylhare** [comment]
So a follow up of the #174 

Let me see:

1. For the first one, you want to add some text to the picture right? 
    - Easy fix is to add it manually to the picture :sweat_smile:. 
    - Or add a new field that you call "caption" you can access it like page.caption in the post.html layout. Try experimenting with the css so it gets displayed as you like :wink: 

2. For the second one, I think you might have to play a bit with the css but try replacing these [lines](https://github.com/sylhare/Type-on-Strap/blob/2abe96439cc57337cd8f381bcf623e0f8329e623/_includes/portfolio.html#L9):
```html
<i class="fa fa-search-plus fa-3x"></i>
```
which is the search icon with something like `{{ item.title }}` which will be the title of the portfolio post.
