### ISSUE TITLE
Author avatar pic in mobile

### ISSUE THREAD

**Issue by wchen02** [sylhare/Type-on-Strap#185]
In the screenshot, sample post and feature image post both have an avatar pic, but the avatar pic in the feature images post is stretched. I observed this in mobile 320px on my blog and the demo blog:
![FireShot Capture 015 - Type on Strap - A website with blog posts and pages - sylhare github io](https://user-images.githubusercontent.com/197353/64327790-22051500-cf81-11e9-8df9-3305c13752b4.png)

**Comment by sylhare** [comment]
Oh! Strange indeed, I'll look into it.

**Comment by sylhare** [comment]
Fix now, thanks ;)
