### ISSUE TITLE
Previous and next swapped. Or is that a matter of preference?

### ISSUE THREAD

**Issue by lehbyte** [sylhare/Type-on-Strap#188]
Hi Sylhare, thanks for this theme;

Shouldn't this;
https://github.com/sylhare/Type-on-Strap/blob/4fc145dd1354a28bb96dd7b7f350b6b19962d459/_includes/post_nav.html#L3
 be  `<div id="next-post">`

--- 

and this;
https://github.com/sylhare/Type-on-Strap/blob/4fc145dd1354a28bb96dd7b7f350b6b19962d459/_includes/post_nav.html#L12
be  `<div id="previous-post">`

Or is that just a matter of preference?

**Comment by sylhare** [comment]
Actually I was also thinking about it. 
Like it makes sens in term of date with the newest post is the first so all before are previous. But then the blog page have `next` that goes the older pages in an inverted manner as within the blog.
Inverting them is not a big deal, I guess I grew used to it 😅 

What do you think should it be all for blog and posts?
`< previous` ... `next >`

**Comment by lehbyte** [comment]
Hi Sylhare!

`<previous ... next>`  makes more sense. 
I mean most people read from left to right so `<next...previous>` is a bit counter-intuitive. 
Cheers :+1:
