### ISSUE TITLE
First page doesn't show socials correctly

### ISSUE THREAD

**Issue by InTheKeyOfCSharp** [sylhare/Type-on-Strap#196]
Hello,

I am currently trying to build a basic blog website with your template. Currently I'm running into an issue where I am trying to get my socials configured for the site via the _config.yml but it seems that the home page doesn't pick up the changes, but as soon as I change to a different page via the next button, it shows all of my social buttons correctly.

Thanks for your help in advance!

**Comment by InTheKeyOfCSharp** [comment]
Never mind I'm sorry! I'm new to Jekyll and Ruby and all of that, I was using --incremental when building locally and it didn't refresh for some reason. Sorry to bother!

**Comment by sylhare** [comment]
Thanks for your using the theme, glad you found the solution :+1:
