### ISSUE TITLE
Why is the excerpt not beeing displayed

### ISSUE THREAD

**Issue by Nikurasukun** [sylhare/Type-on-Strap#198]
I have created a jekyll site with this template and everything is really awesome about this theme, but only the excerpts won't getting displayed. I also used the sample post from here to ensure that the issue isn't the post markdown file.

My fault, because I don't activated excerpt in _config.yml. But please add it Readme, that excerpt must be set to true in the configs

**Comment by sylhare** [comment]
Hi!

Thanks for letting me know, I will add that in the readme ;)
