### ISSUE TITLE
Open YouTube Channel instead of user

### ISSUE THREAD

**Issue by Nikurasukun** [sylhare/Type-on-Strap#199]
When I input my YouTube Name in the _social.yml it opens an other channel, because it tries to open youtube.com/user/Nikurasu and this is an other user. The URL to my channel is:
https://www.youtube.com/channel/UCcwpq3E1Nx-_DDPcBu_c9gg
I also tried to insert my channel ID but this also won't work. How can I Link my channel?

**Comment by sylhare** [comment]
What I can do is add the possibility to add a youtube channel using like a `channel` attribute.
I will work on that

**Comment by sylhare** [comment]
Well user does not make much sens, so I update the documentation for it to use the youtube token of the channel as specified

**Comment by Nikurasukun** [comment]
Thanks, I haven't that much time the last days. But thanks for the reply

**Comment by sylhare** [comment]
Yup, test it and let me if it's all good for you ;)

**Comment by Nikurasukun** [comment]
It works like a charm. Feel free to test it also on www.nikurasu.xyz
