### ISSUE TITLE
Bad feed settings

### ISSUE THREAD

**Issue by RemiBou** [sylhare/Type-on-Strap#200]
Hi,

Type-on-strap uses "jekyll-feed" but if we want to use their feed generation we need to remove the feed.xml file at the root of the template or else the feed will be generated by type-on-strap and the url won't be absolute (here is a better feed : https://remibou.github.io/feed)

For resolving this I have to remove the doc about the feed.xml file and remove the said file. 

If you agree, I can submit a PR.

Thanks for your work BTW

**Comment by sylhare** [comment]
Ah true, I forgot to update the readme about that.
Yeah you can submit a PR, thanks 👍
