### ISSUE TITLE
Social/sharing behaviour with Adblock

### ISSUE THREAD

**Issue by bravina** [sylhare/Type-on-Strap#205]
Hi @sylhare - first of all, thanks for a great design!

I thought I was having issues with the sharing icons and was about to open an issue about it, but I've just realised it's due to using the Adblock plugin in Firefox. It prevents the display of the whole "Share"+icons block at the end of posts, as well as the Facebook and Twitter icons in the social media footer.

Is there a way to prevent this behaviour when using Adblock? Thanks :)

**Comment by sylhare** [comment]
I see that's an adblock issue. It seems you change what you wish to block with it:

https://superuser.com/questions/391556/adblock-like-plugin-for-hiding-social-sites-widgets-buttons-etc

They recommend using the ["Fanboy Annoyance block list"](https://www.fanboy.co.nz/). 
I don't use adblock, let me know if that work for you.

**Comment by sylhare** [comment]
From what I've read they might be blocking it looking at the fontawesome css. I'll see if I can come up with a fix. So you'd be able to see if that works for you.

**Comment by sylhare** [comment]
Well after trying with Adblock, there's nothing I can do to prevent it to hide the social sharing. Unless you specify in the config that you are ok to see it (by default) it will be hidden.
