### ISSUE TITLE
minimist security alert

### ISSUE THREAD

**Issue by jss367** [sylhare/Type-on-Strap#207]
When I fork this I get a security alert saying the version of minimist used in [package-lock.json](https://github.com/sylhare/Type-on-Strap/blob/master/assets/package-lock.json) is too low and needs to be upgraded. Is it possible to upgrade it to >=1.2.3 without breaking anything?

**Comment by sylhare** [comment]
Well minimist is only used in the `gulpfile.js` (used to preprocess images and else) so there are no security alerts for the theme as a website.

I will update the gulp file once an update comes out.

**Comment by sylhare** [comment]
Well it should be good now 😉

**Comment by jss367** [comment]
Thanks!
