### ISSUE TITLE
blog_nav.html command for last page gives incorrect URL

### ISSUE THREAD

**Issue by jss367** [sylhare/Type-on-Strap#208]
The line `site.paginate_path | relative_url | replace: ':num', paginator.total_pages` gives the wrong URL on my page. I don't know if this is because of something I did in the _config.yml or it affects everyone. The relevant part of my config is:

```# Permalink
permalink:   /:title:output_ext

# PAGINATION
paginate: 7
paginate_path: "page:num"
```
This looks fine for the first page, but when you have multiple pages it gives the wrong URL on later pages. For example, from [this page](https://jss367.github.io/page2/) if you scroll down to the bottom the last page icon gives the wrong URL (it directs to `https://jss367.github.io/page2/7` instead of `https://jss367.github.io/page7`).

**Comment by sylhare** [comment]
Hum interesting,

I believe that's because you miss a `/` in your `paginate_path`. 
The default of the theme is the one recommended by the jekyll paginate [documentation](https://jekyllrb.com/docs/pagination/).

However if you want to modify, you may try something like 😉 :

```bash
paginate_path: "/page:num"
```

**Comment by sylhare** [comment]
I have updated the `pagninate_path` per default in the blog so it reflects more precisely the doc 👍

**Comment by jss367** [comment]
That fixed it. Thank you so much!
