### ISSUE TITLE
The RSS feed icon is currently broken

### ISSUE THREAD

**Issue by orion538** [sylhare/Type-on-Strap#210]
I have spotted an issue when showing an RSS icon in the footer because of the following line:
`<a feed.xml href="{{ "" | absolute_url }}" title="{{ site.data.language.str_rss_follow | default: "Follow RSS feed"` in `_includes/icons.html`

I think it should be:
`<a href="{{ "feed.xml" | absolute_url }}" title="{{ site.data.language.str_rss_follow | default: "Follow RSS Feed">`

Or maybe even:
`<a href="{{ site.feed.path | default: "feed.xml" }}" title="{{ site.data.language.str_rss_follow | default: "Follow RSS feed"`

I would have made a PR if I could figure out how to fork the project again. Now I can only point it out (not maintaining a proper branching strategy at the moment).

I did not see the absolute_url being created so I wonder about the variable. Should it not be the `site.feed.path` variable? Because:

`feed:
  path: atom.xml`
As mentioned in: https://github.com/jekyll/jekyll-feed#already-have-a-feed-path

**Comment by sylhare** [comment]
Hi thanks, I will look into it 😉

**Comment by sylhare** [comment]
I added the feed.path in the `social.yml` and put `feed.xml` as default, should be all good now.
I'll close this one 👍
