### ISSUE TITLE
Gallery page shows more images than on assets folder

### ISSUE THREAD

**Issue by sylhare** [sylhare/Type-on-Strap#211]
Hi,

I have an issue with the gallery page on my organizations web (https://thefluxions.github.io/gallery). It shows the pics I added to the pexels folder, but I deleted your pics from the folder and still shows. I checked gallery.md file and gallery.html file and still couldn't find the reason why happens.

By the way, it's a great and flexible design.

Thanks so much in advance :)

_Originally posted by @buenourbano in https://github.com/sylhare/Type-on-Strap/issues/17#issuecomment-623219707_

**Comment by sylhare** [comment]
When I run your website locally I get to see only your two images:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/20642750/80971832-528c9f80-8deb-11ea-8dda-4afb97b4b377.png">

So maybe Github Page does not display the last version, in that case check if you received any message of Github saying so.
Or you maybe you have multiple branches, check which one you choose to be displayed.

If you still have issues, try forking the theme again, or use it as a [remote theme](https://github.com/sylhare/Type-on-Strap#remote-theme) 😉

**Comment by sylhare** [comment]
Seems to be fixed, after forking the project, I'll close it 👍

**Comment by buenourbano** [comment]
Hi sylhare, yes it worked after fork it again and setting it up. I forgot to write here. Thanks so much!
