### ISSUE TITLE
Have blog page outside of index.html completely

### ISSUE THREAD

**Issue by sylhare** [sylhare/Type-on-Strap#212]
So different from #104
This use case would be to use the `home.html` layout or the include `blog.html` to paginate the blog pages outside of the `index.html`.

It seems to be a paginate configuration issue.

Opened by @sylvietht in #17

**Comment by sylvietht** [comment]
Got it! Turns out the paginator doesn't work in any file other than index.html, so I created another index.html file at `/blog/index.html`, where I included the pagination logic. Now when I go to /blog, it displays the paginated posts, and the homepage remains static.

Thanks so much for your help and for that link, it got me on the right path! And thanks again for the fantastic theme.

**Comment by sylhare** [comment]
Ok I found the issue.
What you need to do, if you want to have your blog page outside of `index.html` completely.

```bash
pages
├── ...                       # Other pages
└── index.html         # Your new blog page
```

In your this `pages/index.html` you need to add this which will render the blog page:

```yml
---
layout: home
title: Blog
permalink: /blog/
---
```

And then update the paginator with:

```yml
# PAGINATION
paginate: 5
paginate_path: "/pages/blog/page:num"
```

> By doing so the blog page won't be rendered in the home page, and this one will be empty. You can customize the theme with `blog.html` which is the one actually using the paginator feature.

I still get a `Error reading file ` with the config.yml file though, so I guess there's a more elegant way of doing it.

**Comment by sylhare** [comment]
Thanks @sylvietht I have modified the answer, now I don't get the error with ` No such file or directory @ rb_sysopen ` so I guess we're good for this one 😄

**Comment by sylvietht** [comment]
Great! Thanks, yours looks like a good solution too (especially if one doesn't want to mess with the site navigation as you have it set up).

**Comment by overqint** [comment]
pagination not worked with 
`permalink: /blog/`

after removing, started working
