### ISSUE TITLE
avatar size

### ISSUE THREAD

**Issue by SolZiv** [sylhare/Type-on-Strap#213]
Hi!

Thanks for the theme! I would like to resize the avatar image next to the title of the page in order to use an image of different dimensions than the default, assets\img\triangle.png

Where would I need to do that?

**Comment by sylhare** [comment]
You mean you want to use a different image,
Did you try putting the new image path in the _config.yml?

```yml
avatar: assets/img/triangle.png    
```

For the size, you can try to update the `avatar` css class. Also the [_navbar.scss](https://github.com/sylhare/Type-on-Strap/blob/master/_sass/includes/_navbar.scss) for the style.
