### ISSUE TITLE
Can you please add a optional cookie consent in the theme?

### ISSUE THREAD

**Issue by Nikurasukun** [sylhare/Type-on-Strap#215]
Hey, can you please add a optional cookie consent like [this](https://jekyllcodex.org/without-plugin/cookie-consent/) in your theme. This will be great to make websites that are legal in Europe.

**Comment by sylhare** [comment]
Hum, so I was reading about [gdpr](https://getpublii.com/blog/website-gdpr-compliant.html) for static website, it could indeed apply.

However if the site is based on github.io that means it's not in Europe, so I guess it's a loop hole?
The only thing I see that would make it none compliant would be the use of Google Analytics. Or should it be any js loaded? 

I'll see how the gpdr consent looks like and how I can integrate it.

**Comment by sylhare** [comment]
So after a bit of experimentation, it would look like that.

You could change the cookie consent and the disclaimer phrase in the _config.yml.
However the "More info" button redirects you to a "/privacy" page that you would need to create if you enable it.

I am thinking of adding a default one. Like, the cookies are used for goofle analytics or something.

Desktop
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/20642750/84921214-2e7ed800-b092-11ea-8f67-b7fc111c53b4.png">

Mobile
<img width="362" alt="image" src="https://user-images.githubusercontent.com/20642750/84921156-1b6c0800-b092-11ea-9833-33fa52478a2e.png">

**Comment by sylhare** [comment]
I think I'll remove the More info button as it can be added as a link in the text
