### ISSUE TITLE
Duplicate h1 problem?

### ISSUE THREAD

**Issue by rosepac** [sylhare/Type-on-Strap#238]
Good. I have flight. I was doing some analysis of the website, and I have noticed that some pages. More specifically: [https://sitechecker.pro/](https://sitechecker.pro/). I detect more than one h1 title within hundreds of pages.

You could say that on all fixed pages. That is. The pages that are not part of the blog.
![image](https://user-images.githubusercontent.com/4309005/94328312-bd649000-ffb1-11ea-80f9-5f119dc13c59.png)

I think it may be due to the name of the page. Since an h1 is included to add it.

![image](https://user-images.githubusercontent.com/4309005/94328333-f3097900-ffb1-11ea-8ed8-20ccd5e3d5e8.png)

Everything indicates that it seems that this is the problem. Could be corrected?

I do not know. If this can turn out to be a real problem for Google.

In fact. I have never seen notifications related to a title or h1 related issue in my personal Google Analytics or Google Search Console accounts.

At least I haven't detected it so far.
 But. Just in case.. I leave it here quoted.

I'm sorry for my English. I keep checking more things.
 Thanks for all the hard work.

**Comment by sylhare** [comment]
That's interesting never heard of that kind of issue. I will look into it.

**Comment by sylhare** [comment]
Indeed indeed, it seems to be causing the issue. So I removed the h1 and put the class css attribute directly into the `<a>`.

**Comment by sylhare** [comment]
Should be all good now 👍
