### ISSUE TITLE
Duplicate canonical

### ISSUE THREAD

**Issue by rosepac** [sylhare/Type-on-Strap#239]
The canonical url of the pages is printed in duplicate. Everything indicates that this is due to the use of the jekyll-seo-tag plugin. Plus the included "code" to generate the canonical URL.

This error occurs both in the template and in your personal blog. And obviously it also happened on my website.

-----

I have commented `<link rel="canonical" href="{{ page.url | replace:'index.html','' | absolute_url }}">`in the file `_includes/head.html`. I guess I could delete it

But. I do not know. If exactly it will be the best formula to solve it. But for now. This has been corrected.

-----

P.D.: On your personal blog @sylhare the canonical url is shown with two final slashes. I don't know if that affects performance at all. But it looks a bit strange. I think it is the fault of the final slash of the "base" url of the config page in your site config.

S2 🤗

**Comment by sylhare** [comment]
Yup I will take a look into it . ;)

**Comment by sylhare** [comment]
So after checking, it is indeed part of the jekyll SEO plugin, so I will be removing the manual one that will resolve the duplication.
