### ISSUE TITLE
KateX not loading math

### ISSUE THREAD

**Issue by Ian-Goode** [Sylhare/Type-on-Strap#24]
The KateX package is not working properly at the moment. I have looked through your blog post on markdown and html which has some math to be displayed but it is just being ignored when the site is produced. This same issue is happening to me on my blog. I am not sure what is being done in the KateX java script files but the issue is probably there.

**Comment by Sylhare** [comment]
Allo,

Well on the demo site it looks fine, and on your site too on my side:

![image](https://user-images.githubusercontent.com/20642750/32981815-5847e6f8-cc48-11e7-8eda-3f424cd529c9.png)

Maybe it was a temporary issue with Github page, or the file did not load the first time. Is it still not working on your side?

**Comment by Ian-Goode** [comment]
I was looking at this specific page in your demo, near the bottom where you attempt to use KaTeX. 
https://sylhare.github.io/Type-on-Strap/2014/11/28/markdown-and-html.html
When i look at the .md file I can see that you write out some LaTeX but it isn't showing on the webpage. This is why I don't think KaTeX is working properly.

After I made this post about KaTeX not working I re-implemented the workings of mathjax into the post.html file. That was just a temporary fix and it makes the LateX look blue most of the time but sometimes black, idk why.

**Comment by Sylhare** [comment]
Hum, I will look into it, I might have broken something when minifying the file.

**Comment by Sylhare** [comment]
Yup, it's fixed now ;)

![image](https://user-images.githubusercontent.com/20642750/32984497-8e817c70-cc75-11e7-934d-29b1d20949d4.png)

You can update your site with the latest version. The problem was that the script needs to be loaded after the html is loaded, but since I moved it from the footer to the header, I had to manually say it.
