### ISSUE TITLE
Create an adblock listener and display a deactivation message, in the most correct way?

### ISSUE THREAD

**Issue by rosepac** [sylhare/Type-on-Strap#240]
Good. I am here, I was thinking of creating adblocker plugin deactivation notice message.

For obvious reasons. Small blogs like mine, what little profit they can make is through ads and donations. Unfortunately, nowadays, people are not very tactful about this.

I will be looking into it. In case someone wants to help out, or leave suggestions. All ideas are welcome. I have found how it can be created. [Something like that](https://mycyberuniverse.com/detect-ad-blocker-show-message.html). But I was wondering.

What would be the most correct way to create it? How can it be implemented and that it does not affect the good performance of the page?

S2.

**Comment by sylhare** [comment]
Yup that could be a good idea. You can also create a new include with your disclaimer and then override the default layout to include it.
For the performance of the page it depends on the disclaimer (The more you add of css / js the more it will add to the loading time).
