### ISSUE TITLE
gulp: improve thumbnails task

### ISSUE THREAD

**Issue by mhagnumdw** [sylhare/Type-on-Strap#243]
Hi!

Currently thumbnails are created of all images that are inside the `img` folder. Would it be possible to create only the thumbnails of only the images defined in `feature-img` in the front-matter of the post?

Does that make sense to you?

**Comment by sylhare** [comment]
Yeah so far, it's a very generic task that will create thumbnails for all. I wish the whole gulp tasks would be better.

To create only the feature-img thumbnails ones, that would require to parse through all posts or .md files to check and parse for `feature-img` then apply the change to all those path.
That would require a bit of work that would likely need to be tested. 

As of now I don't have the bandwidth for that, but I agree that would be an interesting feature. Maybe there's already a JS Module for it. If you wanna try it out in a PR feel free, else I will leave it here as an enhancement until I can work on it :wink:

**Comment by sylhare** [comment]
There is a simple solution though.
If you put all of yoiur feature images in a special folder called `feature-img` then we can update the thumbnail gulp to just minimize the pictures in that folder.
And we got a working solution!

I don't think we can do more for now. So if any one go through that and feels like PR, feel free ;)

**Comment by sylhare** [comment]
So with that the gulp tasks have changed a bit

```js
# Targets only the img/feature-img folder
gulp thumbnails 
# Targets all under img
gulp thumbnails-all
```

The thumbnails are now in img/thumbnails (images in that folder are ignored for the gulp task, so it doesn't get "re-thumbnailed").
I also made some clean up in the repo for the not used images, as I believe people can go fetch what they like themselves instead. That will make the whole repo a bit "lighter".
