### ISSUE TITLE
Issue with using datatables. Getting Liquid Exception: liquid syntax error

### ISSUE THREAD

**Issue by discgolfR** [sylhare/Type-on-Strap#244]
Hello - great theme so far!

One persistent problem I'm having is with trying to use datatables. I'm knitting a .Rmd file in a separate directory and then copy-pasting the .HTML into a layout set to "custom". This works fine (although the links in the navbar disappear) as long as I'm not using datatables. 

When I use a datatable created within R DT::datatable() and then copy-paste the HTML into the layout I receive an error like this:

Liquid Exception: Liquid syntax error (line 3213): Variable '{{var c=this,d=b.isDefaultPrevented();a(b.target)}' was not properly terminated with regexp: /\}\}/

Sometimes, if I wrap the lines around the problem area with {% raw %} ... {% endraw %} it works fine, but it's not consistent and also just somewhat of a pain (having to do this anytime I make an update). 

Any wisdom?

**Comment by sylhare** [comment]
Hi thaks for using the theme,

Do you have an example article that you use with the custom layout? (So I can see and try around)
Depending on what type of content you want to display you may need to custom further. 
I am not that familiar with .Rmd, is there a way to export it in .md?

**Comment by discgolfR** [comment]
Hello -

I use the custom layout on this post: https://discgolfdata.com/2021/01/04/Reddits-favorite-discs-part2.html

No way to export Rmd as md as far as I'm aware. It's so I can run R code directly to generate my files. I'm not sure how to "change export attributes so it avoids using liquid syntax" and the javascript suggest is also above my understanding. Apologies for not being familiar with those. I'm just a mere hack! 

Thank you for any help!

**Comment by sylhare** [comment]
Seems more complicated than I thought. The page is heavy on generated stuff. The hacky way would be to put all the `<script></script>` in a different JS.

Or you could try and see this workflow and adapt it [Blogging with Beautiful Jekyll and R Markdown](https://jfiksel.github.io/2017-01-25-hello-world/). 
There seem to be `knitr` that's supposed to make it easier to work with R markdown and Jekyll [support Rmarkdown with knitr](https://gaopinghuang0.github.io/2017/10/23/support-Rmarkdown).

**Comment by discgolfR** [comment]
Yep! My personal website is in Beautiful Jekyll...but I thought I would shake things up with this template!

I'll look into the other link. Thank you!
