### ISSUE TITLE
Add vendor/ to .gitignore

### ISSUE THREAD

**Issue by lbcnz** [sylhare/Type-on-Strap#249]
Shouldn't `vendor/` dir be added to `.gitignore`?

**Comment by sylhare** [comment]
All of the external dependencies are inside the repository.
If you remove them or don't commit them, the associated functionalities would cease to work.

You could remove them if you add the cloudflare links and such to get all the external libraries. But I prefer in this particular case to have all what's necessary for the template to be within it.

**Comment by lbcnz** [comment]
Oh. I forgot there are two *vendor* dirs. I'm referring only to the bundle files at that dir at project root. 

![Screenshot from 2021-02-22 12-31-09](https://user-images.githubusercontent.com/13279154/108730068-edd13b80-7509-11eb-9a8f-bd2e9a8bd479.png)

**Comment by sylhare** [comment]
Oh, you mean you have a `vendor/` directory that gets created when you do either `bundle install` or `bundle exec jekyll serve` ?
I don't recall having this folder 😅

**Comment by lbcnz** [comment]
Yes! :smile:
I added that to my `.gitignore` a long time ago.

**Comment by sylhare** [comment]
Ah true, I had added:

```
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules"]
```

**Comment by sylhare** [comment]
Merged!
