### ISSUE TITLE
Improving assets optimization

### ISSUE THREAD

**Issue by danisztls** [sylhare/Type-on-Strap#250]
Gulp is optimizing already optimized pictures and overwritten the originals so thier quality is probably degrading over time.

In the long term I'm looking for a way to:
- Optimize only non-optimized/new pictures.
- Do that automatically using a pre-commit or pre-push hook.

I'm willing to implement that but first I'm looking for the best way to do that. I can do it  with ImageMagick using a shell script and it would be effective and performant but not every one have it installed in their system so a node package would be more agnostic. I could improve the gulp script but I don't know if gulp is robust enough and it's development is stagnant. But, independently of the tool, I'm thinking on splitting `assets` between `src` and `dist` dirs.

**Comment by sylhare** [comment]
Yes, I have seen the behaviour on some image. Some of them are getting in an endless cycle of being compressed
I tried `sharp` with `gulp-responsive` but it yields the same results.

I am not sure how to tackle that, solving the issue from within the gulp task would be optimal, maybe something in the settings that needs to be passed.

**Comment by sylhare** [comment]
Ok so I am releasing a new version of the theme with all of the previous modification so far.
That way we'll be able to work on the new features that are waiting in your PRs. 👍

**Comment by lbcnz** [comment]
👍🏼

And feel free to drop things that you think that don't add value.
