### ISSUE TITLE
adding page for specific tag

### ISSUE THREAD

**Issue by MaxGrtz** [sylhare/Type-on-Strap#264]
Hi, 

I am currently trying to add an additional page which shows all the posts with a specific tag. 

Is there a recommended way to implement this?

Thank you very much in advance!

Max

**Comment by sylhare** [comment]
Hi, 

To do that I think you would need to copy the tag page and customize it to add check on the wished tags in the display of the articles so that it only displays the articles with that tag.

Try using liquid like `{% unless tag == "wished_tag" %}   {% endunless %} in the for loop.

**Comment by MaxGrtz** [comment]
Thank you very much!
