### ISSUE TITLE
How to add dark mode button

### ISSUE THREAD

**Issue by coder-hex** [sylhare/Type-on-Strap#268]
I wanna enable the dark mode for my site, I updated it yesterday, how to add the dark mode button?

**Comment by coder-hex** [comment]
it's not merged yet, i saw the dark mode PR, and I would like the dark mode to be added.

**Comment by sylhare** [comment]
Yup, it should be added soon, thanks to the awesome PR #262 from @lbcnz 😉

**Comment by coder-hex** [comment]
Thanks a lot! I thought it was available since I saw the PR, thanks!

**Comment by coder-hex** [comment]
Oh yeah, an idea, can you try to add a mode that makes it turn to dark mode at 6 pm and Light Mode at 7 AM? Like timed switching type?

**Comment by coder-hex** [comment]
When will the dark mode be added? I can't wait for this!

**Comment by sylhare** [comment]
😅 I hope to have it within this week. I need to make a lot of verification since it touches key layout components

**Comment by sylhare** [comment]
@coder-hex it's on 😎
If you have any issue let me now.

**Comment by coder-hex** [comment]
Dark mode is gonna get on my main blog!
Thanks Sylhare!

**Comment by coder-hex** [comment]
It is working nicely!
