### ISSUE TITLE
katex autorender

### ISSUE THREAD

**Issue by MaxGrtz** [sylhare/Type-on-Strap#276]
Hi,
first, thank you very much for the nice template :D

I am struggling to have katex render environments like this one:

\begin{CD}
   A @>a>> B \\
@VbVV @AAcA \\
   C @= D
\end{CD}

which are supported according to https://katex.org/docs/supported.html.
According to the documentation: 

The auto-render extension will render the following environments even if they are not inside math delimiters such as $$…$$. They are display-mode only. ....

I also tried wrapping the environment into $$..$$, but both versions won't render. 

**The same goes for the equation and split environments.** 

Finally, I tried to adjust the auto-render.min,js file to change the delimiters, such that inline math is indicated by $...$
and $$...$$ indicates display mode, but this does not seem to work either.

I would be grateful for any tips oder ideas on how to solve this issue!

Thank you very much :)

EDIT: 
Everything works as expected if I turn of katex in the config file and include:

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.5/dist/katex.min.css" integrity="sha384-L+Gq2Cso/Y2x8fX4wausgiZT8z0QPZz7OqPuz4YqAycQJyrJT9NRLpjFBD6zlOia" crossorigin="anonymous">
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.5/dist/katex.min.js" integrity="sha384-z64WtjpyrKFsxox9eI4SI8eM9toXdoYeWb5Qh+8PO+eG54Bv9BZqf9xNhlcLf/sA" crossorigin="anonymous"></script>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.5/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
    onload="renderMathInElement(document.body);"></script>

in the header.html file.

**Comment by sylhare** [comment]
Thanks I will take a look at it. 
Do you have a link to your blog where I can have a look at the version you are using (or does the problem happen with the current version)?

**Comment by sylhare** [comment]
I tried with KaTex v0.13.5 and could not manage to make it display event with the library from cdn:

```html
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.5/dist/katex.min.js" integrity="sha384-z64WtjpyrKFsxox9eI4SI8eM9toXdoYeWb5Qh+8PO+eG54Bv9BZqf9xNhlcLf/sA" crossorigin="anonymous"></script> <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.5/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous" onload="renderMathInElement(document.body);"></script> 
```

I'll update KaTex version and try out more.

**Comment by sylhare** [comment]
Ok syntax error, I'll update the version and now it's working

**Comment by sylhare** [comment]
You can see it working [here](https://sylhare.github.io/Type-on-Strap/2021/04/27/dark-mode.html)
