### ISSUE TITLE
> This works for me. I'm wondering if this is going to be considered a bug ([pytest-dev/pytest-cov#468](https://github.com/pytest-dev/pytest-cov/issues/468)). In any case, this fix is needed for `pytest_cov=={2.10.1,2.11.0,2.11.1}`.

### ISSUE THREAD

**Issue by akiragg** [sylhare/Type-on-Strap#285]
> This works for me. I'm wondering if this is going to be considered a bug ([pytest-dev/pytest-cov#468](https://github.com/pytest-dev/pytest-cov/issues/468)). In any case, this fix is needed for `pytest_cov=={2.10.1,2.11.0,2.11.1}`.

It was considered a bug and fixed: https://github.com/pytest-dev/pytest-cov/commit/f5a4d7e008087913ce2bc9dc2305d05a5f545a41. So it should be fine for `>2.11.1`, but for `2.10.1` to `2.11.1` we need this PR.

__最初由 @christophebedard 在 https://github.com/colcon/colcon-core/pull/434#issuecomment-840564248 发布__

**Comment by sylhare** [comment]
@akiragg maybe that's the wrong place for this issue, I'll be closing it ;)
