### ISSUE TITLE
Table of contents

### ISSUE THREAD

**Issue by coder-lg** [sylhare/Type-on-Strap#287]
How do you add a TOC in a markdown file here? Because, my editor can input TOCs via this method:`{:toc}`. How do you add to a blog on Type on Strap?

**Comment by coder-lg** [comment]
@sylhare can you please tell how to add toc to a blog

**Comment by sylhare** [comment]
This `{:toc}` should be the default way with kramdown and it should be pretty much automatic according to the [doc](https://kramdown.gettalong.org/converter/html.html#toc), as to why it does not render, I am not sure.

**Comment by sylhare** [comment]
Did you try like in the [article](https://raw.githubusercontent.com/sylhare/Type-on-Strap/master/_posts/2013-12-12-Generate-a-table-of-content.md) with at least one `h1` with `#` header?

```html
* TOC
{:toc}
```

**Comment by coder-lg** [comment]
Yes

**Comment by coder-lg** [comment]
it works now
