### ISSUE TITLE
If portfolio is disabled, it disables search and tags too

### ISSUE THREAD

**Issue by mattinsalto** [Sylhare/Type-on-Strap#29]
Hello, 
First of all, congratulations for the theme, in my opinion, one of the bests for Jekyll.
In _includes -> navbar.html there is the same if condition 
`{% if site.theme_settings.portfolio %}`
for _portfolio, search and tags_ so disabling _portfolio_ the others don't appear either

**Comment by Sylhare** [comment]
Indeed I will correct that

**Comment by Sylhare** [comment]
Should be good now.
