### ISSUE TITLE
Some error with Matrix icon

### ISSUE THREAD

**Issue by coder-lg** [sylhare/Type-on-Strap#292]
So, as usual, downloaded the repository via zip, set up everything and all. I added the Matrix username but it didn't work, ie, If I hover over the icon when it is default, which is `https://matrix.org/#/`, it just shows that URL. It starts working only when I add my username inside the icons builder file.

**Comment by sylhare** [comment]
I'll look into it

**Comment by sylhare** [comment]
Indeed there was something I missed I have updated it and it should work now 😉

**Comment by coder-lg** [comment]
now it works successfully
