### ISSUE TITLE
Glitch: Scroll Bar appearing on Katex snippet

### ISSUE THREAD

**Issue by danisztls** [sylhare/Type-on-Strap#294]
Browsing the demo I stumbled upon this.

![Screenshot from 2021-06-25 22-17-38](https://user-images.githubusercontent.com/13279154/123497349-6b659f00-d603-11eb-8cfa-67f0d87ecdda.png)

https://sylhare.github.io/Type-on-Strap/2014/11/28/markdown-and-html.html

**Comment by coder-lg** [comment]
@danisztls it's nothing. I checked it and came to the conclusion that if the problem(Katex math problem) is big and there isn't enough space, it compresses and adds the scroll bar to scroll the problem.

**Comment by coder-lg** [comment]
observed on other sites too

**Comment by sylhare** [comment]
Indeed, the only issue is that Firefox has an ugly scrollbar compared to other browser. :sweat_smile:

**Comment by danisztls** [comment]
@sylhare That's on Chromium.

**Comment by sylhare** [comment]
Alright cool, I'll add an extra long equation and put your fix to the test 😛

**Comment by sylhare** [comment]
Well after testing making the overflow visible is too risky, so we'll leave it as is. But it could be something to be solved by the KaTex team :+1:
