### ISSUE TITLE
Workflow PR request(pr ready at #298)

### ISSUE THREAD

**Issue by coder-lg** [sylhare/Type-on-Strap#297]
So, I have spent the last week learning in GitHub and got an interest in GitHub Actions. And today came a question. 
Can I make a PR here for adding GitHub Actions and an app(the main star here), `release-drafter` which helps in drafting releases when PRs are merged and shows the changes like lists. 
SO, I wanted to ask if I could make a PR for this. 
You need to do some small things if you allow me for a PR, which are:

- [x] IF you allow me, you have to make a GitHub repo project for bug triage(the pr is full-on efficiency)
- [x] Install the [`release-drafter`](https://probot.github.io/apps/release-drafter/), [`stale`](https://probot.github.io/apps/stale/), and [`request-info`](https://probot.github.io/apps/request-info/) app from GitHub's [Probot](https://probot.github.io/) Apps __*after*__ merging the PR, if allowed

If yes, please say yes and I will start working on the PR immediately. It will have a TON of actions, but some of them do work. I will keep the working ones only.
And, if you allow me for a PR, install [`wip`](https://probot.github.io/apps/wip/), because it doesn't need config. It won't allow the merges of PRs if the beginning of the PR is `WIP: {{pr-name}}` where `{{pr-name}}` is your PR's name. WIP will get a request and act as if it is checking, therefore blocking the PR to be merged.

**Comment by coder-lg** [comment]
And, an action I add will have a function to add labels to PRs, if the title is starting with `WIP`

**Comment by coder-lg** [comment]
Only for @sylhare

**Comment by sylhare** [comment]
Hi, can the GitHub repo for bug triage be this one? I'd rather have the questions and bugs about the theme in the same repository.

You can give it a try, I was thinking of migrating from travis to github action for the pipeline as well.

**Comment by coder-lg** [comment]
I see that you haven't made the project yet. Just open this repo, hit the [`Projects`](https://github.com/sylhare/Type-on-Strap/projects) and click the New project button. Then, name it as Bugs and click the drop-down. Then, hit Bug Triage and save the project. This will help later so try to allow me in that project too. It is related to an action I am going to add.

**Comment by coder-lg** [comment]
To know more about them, just go to the [`GitHub Learning Lab`](https://lab.github.com) and check every course related to GitHub Actions. I strongly guess it has to be the one related to GitHub Script. Try that course and it will show that the Bug triage project you made is important.

**Comment by coder-lg** [comment]
oh yeah, you don't need to grant access to projects but you MUST create it. I will try to find an action/Probot app for marking issues with labels based on titles. And, you must have to make an instructions for issues/PRs issue, pin it and I will try to make an app which can add a reply to read that issue.

**Comment by coder-lg** [comment]
I am sure it will work btw :wink: i practised these.

**Comment by coder-lg** [comment]
I will refer the issue in the PR I make, all YOU got to do right now is install WIP, mentioned in the description to this repo only. WHen you have done it, just tell me here.

**Comment by coder-lg** [comment]
> So, I have spent the last week learning in GitHub and got an interest in GitHub Actions. And today came a question. 
> Can I make a PR here for adding GitHub Actions and an app(the main star here), `release-drafter` which helps in drafting releases when PRs are merged and shows the changes like lists. 
> SO, I wanted to ask if I could make a PR for this. 
> You need to do some small things if you allow me for a PR, which are:
> 
> - [ ] Install the [`release-drafter`](https://probot.github.io/apps/release-drafter/), [`stale`](https://probot.github.io/apps/stale/), and [`request-info`](https://probot.github.io/apps/request-info/) app from GitHub's [Probot](https://probot.github.io/) Apps __*after*__ merging the PR, if allowed
> - [ ] IF you allow me, you have to make a GitHub repo project for bug triage(the pr is full-on efficiency)
> 
> If yes, please say yes and I will start working on the PR immediately. It will have a TON of actions, but some of them do work. I will keep the working ones only.
> And, if you allow me for a PR, install [`wip`](https://probot.github.io/apps/wip/), because it doesn't need config. It won't allow the merges of PRs if the beginning of the PR is `WIP: {{pr-name}}` where `{{pr-name}}` is your PR's name. WIP will get a request and act as if it is checking, therefore blocking the PR to be merged.

Refer this and pr at #298

**Comment by sylhare** [comment]
I got the project created https://github.com/sylhare/Type-on-Strap/projects/2?add_cards_query=is%3Aopen

**Comment by coder-lg** [comment]
Thanks!

**Comment by coder-lg** [comment]
So, I see you started a course, Release based workflow. You better take the course on getting started with GitHub Apps. That will help you with my PR.

**Comment by sylhare** [comment]
Yup I'll follow the course first then I'll see for here 👍

**Comment by coder-lg** [comment]
You even do Getting started with GitHub Apps. It contains info for WIP and request info apps.

**Comment by coder-lg** [comment]
Check #301, it has the needed workflows. It has a LOT of workflows that you need to see.

**Comment by sylhare** [comment]
Well that's the issue, I would rather have one PR per workflows otherwise I can't merge it, too many things at once.

**Comment by coder-lg** [comment]
Ooookaay...

**Comment by coder-lg** [comment]
Why not 2 workflows in one PR?

**Comment by sylhare** [comment]
One PR one feature. It's easier to see what does what.

**Comment by coder-lg** [comment]
Okay. I need this week off for the PRs. Will be busy though.

**Comment by coder-lg** [comment]
check #304 , #305 , #306 , #307 , #308 for the PRs.

**Comment by coder-lg** [comment]
ping @sylhare

**Comment by sylhare** [comment]
I will close this issue since the PR are already there.
I don't think I need it as of now since I don't have that many issues coming in. But it might get handy in the future so I'll leave them there and merge once needed :+1:

**Comment by coder-lg** [comment]
Well, merge #305 and #308, it is because 305 has a comment action, and ONLY that. 308 has the templates(bug report, feature request, comment file for 305.) Merge that because, you need that.
