### ISSUE TITLE
Comments from utterances doesn't seem to show up.

### ISSUE THREAD

**Issue by rsnpj** [sylhare/Type-on-Strap#302]
![image](https://user-images.githubusercontent.com/56220537/125547771-60f3819f-d168-4a17-b805-806445e50512.png)

I added the required config in _config.yaml. Comment box doesn't show up in blog posts. What am I doing wrong? Utterances is installed and access is grated to all repos.

**Comment by rsnpj** [comment]
I should have read the docs dammit.

**Comment by coder-lg** [comment]
Apply the theme, it is compulsory. Since I made the PR for Utterances, I know that. Sylhare might have removed theme and label arguments. Will try to fix that.

**Comment by coder-lg** [comment]
Somewhat like `github-dark`

**Comment by coder-lg** [comment]
I will try to ask @sylhare to fix that

**Comment by coder-lg** [comment]
Opened an issue for this issue, will deliver fixes for this.

**Comment by coder-lg** [comment]
Hey @rsnpj, made a PR and linked it to this issue. Will be fixed. Meanwhile, you gotta put the args manually. Refer #303 for info.

**Comment by rsnpj** [comment]
Yes, it is fixed as of now. Thank you.

**Comment by coder-lg** [comment]
You keep this issue open until the fix is merged.

**Comment by rsnpj** [comment]
@coder-lg Hey, that issue is fixed but it turns out if I comment on a page, it shows up on all the pages. Shall I open a new issue for it?

**Comment by coder-lg** [comment]
That ain't possible. Lemme check later.

**Comment by coder-lg** [comment]
Try changing the issue-term argument to title.

**Comment by coder-lg** [comment]
And, remove the double quotes. Always works without them.

**Comment by rsnpj** [comment]
Changing the issue-term to title and removing double quotes worked!! Thanks.

**Comment by coder-lg** [comment]
Knew it.

**Comment by coder-lg** [comment]
Don't close this until the PR is merged. It's a good fix.

**Comment by coder-lg** [comment]
> Changing the issue-term to title and removing double quotes worked!! Thanks.

I suspect it was the double quotes that did the work. But, using title is helpful, since you can search your title in the issues section.

**Comment by rsnpj** [comment]
Yes. I just followed the readme. You guys should specify (without the double quotes), that would save future folks a lot of headache.

**Comment by rsnpj** [comment]
Also, the theme property will support automatic in future right? github-light theme in website dark theme doesn'e look good and vice versa.

**Comment by coder-lg** [comment]
Maybe. Sylhare suggested color-theme, not tested tho.

**Comment by coder-lg** [comment]
Commented at your site. I say that you use github-dark because it works well in dark mode and looks good in normal mode.

**Comment by coder-lg** [comment]
> Yes. I just followed the readme. You guys should specify (without the double quotes), that would save future folks a lot of headache.

Adding that to the changes too. Good idea dude!

**Comment by rsnpj** [comment]
> Commented at your site. I say that you use github-dark because it works well in dark mode and looks good in normal mode.

But, I am a light-mode guy. :D  I will just leave as is or might wrap the comment section inside a div with a cool looking picture or sth.

**Comment by coder-lg** [comment]
Try `color-theme` in the theme argument. It was given in the README.

**Comment by rsnpj** [comment]
color-theme and color_theme both didn't work. The comment box disappeared. github-dark-orange did look a little better. Where do I get such custom themes (like the github-dark-orange)?

**Comment by coder-lg** [comment]
at [utteranc.es](https://utteranc.es)

**Comment by rsnpj** [comment]
`        theme="{% if site.comments.utterances.theme %}{{ site.comments.utterances.theme }}{% elsif site.color_theme == 'dark' %}github-dark{% else %}github-light{% endif %}"`

How should I change this line so that the theme is changed to github-dark on dark mode and github-light on light mode?

**Comment by rsnpj** [comment]
kinda like this: https://tysonwilliams.coding.blog/2021-06-21_lock_hunter

**Comment by rsnpj** [comment]
seems possible with that line but the site.color_theme is not working I think

**Comment by coder-lg** [comment]
well idk but it might be long lines of code. you can't use html on yaml. that syntax 
```html
{{ site.whatever }} <!--is used only on html for yaml inclusion-->
```
THis is done so that your variables on that html can be in one place, the config.

**Comment by coder-lg** [comment]
lemme analyse that code and report back.

**Comment by rsnpj** [comment]
oh, cool.

**Comment by coder-lg** [comment]
there is no code for that page, like it is private or something.

**Comment by rsnpj** [comment]
Okay then. Please talk with @sylhare and fix the color_theme. This theme is so cool for blogs. I love it !!

**Comment by coder-lg** [comment]
will check about that.

**Comment by sylhare** [comment]
So I guess this is linked to #303 and #310

**Comment by coder-lg** [comment]
yup

**Comment by coder-lg** [comment]
testing `color_theme` if it works

**Comment by sylhare** [comment]
Fixed ;)

**Comment by coder-lg** [comment]
okay. but is there a method to change themes automatically?

**Comment by sylhare** [comment]
Nope unless utterance makes it so
