### ISSUE TITLE
Arguments missing for utterances in config.yml file

### ISSUE THREAD

**Issue by coder-lg** [sylhare/Type-on-Strap#303]
@sylhare,
You missed an argument in the `_config.yml` file on Utterances.
In the `utterances:` set of args, you missed this:
```yaml
theme:
label:
```
These are compulsory(label isn't but user's choice right?), and there is an issue which is #302 but I fixed that. Will open a PR to fix that globally.
This is high priority right now as Utterances needs a theme to work. Will deliver a fix for Utterances.
After adding workflows, the main task is:
- [ ] Fix bug in Utterances (related to #302 and #303)

**Comment by coder-lg** [comment]
Added PR

**Comment by sylhare** [comment]
Fixed

**Comment by coder-lg** [comment]
:+1:
