### ISSUE TITLE
Search breaks when there are double quotes inside {% highlight terminal %}

### ISSUE THREAD

**Issue by mattinsalto** [Sylhare/Type-on-Strap#31]
Hello, search breaks when there are double quotes inside `{% highlight terminal %}`. I supose it will break search in other _highlights_ too
For example:
```
{% highlight terminal %}
...
Init4 = AT+CGDCONT=1,"IP","internetmas","",0,0
...
{% endhighlight %}
```
breaks it.
To fix it, you could change _post_ and _portfolio_  _content_ search in _layouts -> search.hml
from 
`"content"  : "{{ post.content | strip_html | strip_newlines }}"`
to
`"content"  : "{{ post.content | strip_html | strip_newlines | replace: '"', '\\"' }}"`

Thanks

**Comment by Sylhare** [comment]
Thanks, I will give it a try ;)

**Comment by Sylhare** [comment]
It is now working thanks!
