### ISSUE TITLE
color_theme argument for theme doesn't work

### ISSUE THREAD

**Issue by coder-lg** [sylhare/Type-on-Strap#310]
@sylhare,
I gotta say, there are a lot of problems in Utterances. The `color_theme` syntax in the readme doesn't work literally. More things and questions here. In #302, that error got solved but how can you make the comment system shift themes? Like, light for light and dark for dark. A literal question: Can I add those code lines that do some sort of thing like shifting themes in the config like this:
```
{{ site.theme-change-automatically  }} 
```
I and another user related to #302 are interested in that. Is there any kind of workaround for that?

**Comment by sylhare** [comment]
Well utterance doesn't work with auto theme doing `{{ site.theme-change-automatically  }} ` won't make it change automatically unless they have added the `auto` in their theme choice

**Comment by coder-lg** [comment]
What if they did?

**Comment by sylhare** [comment]
Fixed
