### ISSUE TITLE
Can this theme use TypeScript? (For utterances dymanic color change)

### ISSUE THREAD

**Issue by im-coder-lg** [sylhare/Type-on-Strap#311]
Got a question. Can I use TypeScript here? Because, in #302, I got a question, how to change Utterances color dynamically as the theme color changes. So, how can I get Typescript here if I can, or if I can't, how to get it here?

**Comment by sylhare** [comment]
Allow, as of now it is not possible, you could use a javascript script like we did for the dark-theme, if utterances doesn't offer the possibility.

**Comment by danisztls** [comment]
That reminded me that I am postponing updating Cusdis integration to support this:
https://github.com/djyde/cusdis/issues/59#issuecomment-835123606

**Comment by coder-lg** [comment]
Well, any kind of plugins for that? Because, I found a method to change Utterances color dynamically with TS(TypeScript)

**Comment by danisztls** [comment]
TypeScript compiles to JS.

**Comment by coder-lg** [comment]
So, I will add links to two files. Can I convert them to JS from TS?

**Comment by coder-lg** [comment]
And how?

**Comment by sylhare** [comment]
> Well, any kind of plugins for that? Because, I found a method to change Utterances color dynamically with TS(TypeScript)

Do you have the link to that?

**Comment by coder-lg** [comment]
it's on #302, some guy named Tyson Williams' Blog, the link is there.

**Comment by coder-lg** [comment]
This link: https://tysonwilliams.coding.blog/2021-06-21_lock_hunter

_Originally posted by @rsnpj in https://github.com/sylhare/Type-on-Strap/issues/302#issuecomment-879621029_

**Comment by sylhare** [comment]
Yes that's a post article where it is indeed working, however you talked about Typescript code in utterances to allow that. Do you have a link to the procedure with the typescript code to enable utterances to auto change theme?

**Comment by coder-lg** [comment]
In that blog, at the end, he gave some link to edit his files. I went there, went to the root directory and went into the `.codedoc` directory. Then, I got into `components` or something like that and checked it there. I will post the link to the utterances dir here. One min...

**Comment by coder-lg** [comment]
In that blog, at the end, he gave some link to edit his files. I went there, went to the root directory and went into the `.codedoc` directory. Then, I got into `components` or something like that and checked it there. I will post the link to the utterances dir here. One min...

**Comment by coder-lg** [comment]
Is that a glitch?

**Comment by sylhare** [comment]
I guess so I deleted it

**Comment by coder-lg** [comment]
Ok...

**Comment by coder-lg** [comment]
The TS code was short, like less than 10 lines too.

**Comment by sylhare** [comment]
> In that blog, at the end, he gave some link to edit his files. I went there, went to the root directory and went into the `.codedoc` directory. Then, I got into `components` or something like that and checked it there. I will post the link to the utterances dir here. One min...

Where is that code? I can't find it. Can you paste it?

**Comment by coder-lg** [comment]
This one: https://github.com/TysonMN/tyson-williams-blog/tree/master/.codedoc/components/utterances

**Comment by coder-lg** [comment]
I has two files, a normal TS file with those lines and another style file.

**Comment by sylhare** [comment]
Humm then maybe we can do it via js the same we did for cusdis:

I paste it here for ref:

```ts
import { themedStyle } from '@connectv/jss-theme';
import { CodedocTheme } from '@codedoc/core';


export const UtterancesStyle = themedStyle<CodedocTheme>(_ => ({
utterancesTransparentIframe: {
   '& iframe.utterances-frame': { background: 'transparent' },
 }
}));
```

**Comment by coder-lg** [comment]
How do we do that? New to JS that's why.

**Comment by coder-lg** [comment]
Moreover, we need that codedoc dependency

**Comment by coder-lg** [comment]
lemme try that same thing in my gitpod.

**Comment by coder-lg** [comment]
yo @sylhare check this: https://3000-salmon-swallow-p0pcmux1.ws-us11.gitpod.io/2021-06-21_lock_hunter
basically I forked the repo and opened it in my gitpod.
Then, got the dependencies via codedoc and voila! this is how it gotta work.

**Comment by sylhare** [comment]
Basically when you change the theme, you would need to load a new div with the utterances comments but with the new theme in `theme`

**Comment by coder-lg** [comment]
yup, maybe? did you check the gitpod link i put above?

**Comment by coder-lg** [comment]
okay, i am pausing the gitpod workspace, but will open it later. tired as of now and got some work too.
I will open it soon AND give access to you and @danisztls because I think he is a JavaScript expert.

**Comment by danisztls** [comment]
Wow! So many dependencies.

**Comment by danisztls** [comment]
> okay, i am pausing the gitpod workspace, but will open it later. tired as of now and got some work too.
> I will open it soon AND give access to you and @danisztls because I think he is a JavaScript expert.

Nah. I can hack things when I put time and effort but I never used TypeScript.

**Comment by coder-lg** [comment]
Well, I think TS is same as JS. Need your idea too tho.

**Comment by sylhare** [comment]
Anyway jekyll is a static site, so let's not create too much code for something that should go to utterances. You can create a ticket in their project to give a way to handle dark / light theme changes with `data-theme`.

**Comment by danisztls** [comment]
TS is a superset of JS, it has more language features (syntactic sugar) aimed at OOP and higher abstraction but they are close.

**Comment by danisztls** [comment]
Look here. https://github.com/sylhare/Type-on-Strap/blob/05926f38caf0c7a90406b141f865915529482630/_includes/social/utterances.html

And here https://github.com/sylhare/Type-on-Strap/blob/master/assets/js/partials/dark-mode.js

Instead of setting Utterances theme from site config you can write a script to init it. You can listen for changes on session storage and get the theme data that dark mode script set.

But what I recommend is that you open an issue on the project as it current design is bad. It would a lot simpler and easier if Utterances used CSS variables for theming. Also, unless your site looks similar to Github, the comments section will have an alien look with different colors and fonts.

**Comment by coder-lg** [comment]
>But what I recommend is that you open an issue on the project as it current design is bad.

Yup, since I wanted to know about it, I opened one at utterance/utterances and noticed that others also asked for it.

**Comment by coder-lg** [comment]
But they use SCSS which I think is a form of CSS. WHy do we need only CSS?

**Comment by danisztls** [comment]
@coder-lg SCSS is not dynamic. It compiles to CSS. By having multiple CSS data structs (aka themes) you can use JS and/or `prefers-color-scheme` to set theme on the fly. Look at `_variables.scss` for reference. The implementation of Sass that Jekyll (and most others) use don't even work with themes. Try using a Sass variable as a value for a variable it would be interpreted as a literal.

**Comment by coder-lg** [comment]
I did not understand that. But can you change it dynamically?

**Comment by coder-lg** [comment]
I think it is because of [`coding.blog`](https://coding.blog). Because, it is a domain hoster and uses TS

**Comment by coder-lg** [comment]
moreover, it was actually a plugin or something of sorts by Connect Platform, the maker of coding.blog. I asked Tyson Williams and he told that it was a prebuilt plugin that sends multiple requests and doesn't use CSS. It uses prebuilt themes of Utterances and changes it like that. That code @sylhare put above was the final edition. The original code was in the `src` directory.

**Comment by coder-lg** [comment]
https://github.com/TysonMN/tyson-williams-blog/issues/33#issuecomment-881801786
If you look at that comment, he says that he adds the code to his markdown and then it gets extracted to a separate component. I signed up for a domain as codedoc to check how it works. Will see that and report here. Till then, I would close this issue. When I reopen, I will give the result I got.

**Comment by TysonMN** [comment]
I am not very good at web programming, so I can't directly contribute to this conversation.  @loreanvictor is the lead developer of CODEDOC.  Many he can help you understand how CODEDOC's `DarkLight` component works.

**Comment by coder-lg** [comment]
I understood that, @TysonMN but the dilemma is, how to convert TS to JS? This is a Jekyll site that's why.

**Comment by TysonMN** [comment]
My understanding of TS is that it can be used anywhere JS is used because part of the build process is transpiling TS to JS.

**Comment by sylhare** [comment]
I link the utterances issue that you created here: https://github.com/utterance/utterances/issues/549
I'd rather not try to hack the codedoc typescript component to make it work here.

**Comment by im-coder-lg** [comment]
So, almost a month since I got the CODEDOC blog, and it is really dynamic. It has two files, a style file for the styling and an index file where you add th repo, label, issue name, and theme(in config?), so, if we try recreating that with HTML, JS and TS, and add some more configuration in the config, it might work, right?

**Comment by im-coder-lg** [comment]
Suggestion: using JSX, because JSX is JS and HRML combined, might work.

**Comment by sylhare** [comment]
I will close this one for now.
