### ISSUE TITLE
 Is there a way to sort by date in portfolio page?

### ISSUE THREAD

**Issue by sieunju** [sylhare/Type-on-Strap#315]
The file names are displayed in A-Z order on the portfolio page. Is there no way to sort by date in MarkDown file?

**Comment by sieunju** [comment]
Add Comment 
Date in latest!! 
Help Me...
😭

**Comment by im-coder-lg** [comment]
Well, idk but have you tried adding the date to the portfolio? 

And,

/ping @sylhare and sorry sylhare that I was offline here.

**Comment by sieunju** [comment]
@im-coder-lg 
Yes, Add Date portfolio.md
Example
---
layout: post
title: text
date: 2017-09-01
---

**Comment by im-coder-lg** [comment]
wait wdym?

**Comment by sieunju** [comment]
> wait wdym?

Yes, I added it.
When added, exposure is made in historical order by date.
I'd like to expose it in the latest order based on the date.

**Comment by im-coder-lg** [comment]
Well, this is advanced. Pinging @sylhare

**Comment by sylhare** [comment]
If you name your file using the dates at the beginning that should solve your issue
