### ISSUE TITLE
How to add a markdown essay  outline?

### ISSUE THREAD

**Issue by accordionmaster** [sylhare/Type-on-Strap#318]
Hello, I want to know  how to add an essay outline which used by markdown , thanks!

**Comment by im-coder-lg** [comment]
I don't think essay outlines exist but you can use the core Markdown syntax to make big lines for separating things of your choice with `***` or `------`.

**Comment by sylhare** [comment]
You could use some html + css as well to create your own (via a css class on a html element like `<div class="outline"> </div>` and you make it full width and underline gray) then add it in your markdown file and it will be rendered.
