### ISSUE TITLE
Is Type On Strap still active today?

### ISSUE THREAD

**Issue by im-coder-lg** [sylhare/Type-on-Strap#331]
I have noticed less commits than before, is Type on Strap still active?

**Comment by sylhare** [comment]
Yes, it's always open for new features. The responsive image sizing would be one of the next feature I'd like to have 🤔

**Comment by im-coder-lg** [comment]
Yeah, but since there are rare commits, are there possibilities that this would go offline for a long period of time?

**Comment by sylhare** [comment]
Well for a jekyll theme, as long as the repo is here it can be used. As for activity I am still adding features to it with no schedule.
Any PR is welcome, sometimes we have more contributors, sometimes less.
I am going to close this one now.
