### ISSUE TITLE
Posts not showing up on home page (or anywhere)

### ISSUE THREAD

**Issue by julia-neme** [sylhare/Type-on-Strap#341]
Hi sylhare!! First of all, great template and thank you so much for making it available!

I am having trouble generating posts. For some reason, they are not appearing on my site, and I have no clue what is going on.

[My site](https://julia-neme.github.io/)

[github repo](https://github.com/julia-neme/julia-neme.github.io/blob/master/_posts/2022-04-26-first-post.md)

Thank you so much in advance :)

**Comment by im-coder-lg** [comment]
Hmm, I haven't seen that myself. My website also has Type on Strap but I never encountered this! Have you messed with pagination?

**Comment by julia-neme** [comment]
Where could I check pagination? Sorry, I'm a complete newb at this

**Comment by im-coder-lg** [comment]
I think in _config.json, there should be a pagination line that was fixed at 5. You messed it up?

**Comment by julia-neme** [comment]
Yep that was it, thank you so much!

**Comment by im-coder-lg** [comment]
Wow, I never expected it. True, @danisztls had mentioned that pagination messed things up big time, but I never knew this came so far till here! @sylhare is it common for pagination errors in Jekyll?

**Comment by danisztls** [comment]
> Wow, I never expected it. True, @danisztls had mentioned that pagination messed things up big time, but I never knew this came so far till here! @sylhare is it common for pagination errors in Jekyll?

For the scope of the theme I don't think it would mess things and pagination issues here are probably due to misconfiguration. Though, from my own experience, Jekyll default pagination doesn't cut for multi-language sites and collections. And for that cases I use 'jekyll-paginate-v2'.
