### ISSUE TITLE
Images get squashed if specifying width and height HTML tags

### ISSUE THREAD

**Issue by jtc** [Sylhare/Type-on-Strap#36]
If one specifies both a width and a height tag when inserting an image through HTML, the image gets squished in width. This seems to be due to the padding of images.

I've put up a demo of this issue at the links below, using a square image so it is clear to see when it gets squished.

Published site: https://jtc.github.io/Type-on-Strap-width-demo/2017/12/12/image-width-issue.html
Repository: https://github.com/jtc/Type-on-Strap-width-demo/blob/master/_posts/2017-12-12-image-width-issue.md

If you specify height only it is fine. If you specify width only, the image doesn't get squished, but it does get resized quite smaller than was specified.

**Comment by Sylhare** [comment]
Oh nice catch!
I will look into this one, thanks.

**Comment by Sylhare** [comment]
@jtc 
well the size is working fine, 

However the only thing is that images have a default width padding of 10%. So if you want to change the size of your image manually try with relative size using % instead.

**Comment by jtc** [comment]
Ah, of course, will try relative sizing.

Thanks for looking into this @Sylhare and the great theme 😃
