### ISSUE TITLE
Workflow action - Getting Error: The process '/opt/hostedtoolcache/Ruby/2.7.2/x64/bin/bundle' failed with exit code 16

### ISSUE THREAD

**Issue by mjh2901** [sylhare/Type-on-Strap#362]
**Describe the bug**
When rendering in github pages it is launching 2 jobs and i am getting a error on one, the other which is the page build does finish green and th pages render

Run ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
Downloading Ruby
Extracting Ruby
Installing Bundler
bundle install
Error: The process '/opt/hostedtoolcache/Ruby/2.[7](https://github.com/mjh2901/mikehathaway/runs/8276917729?check_suite_focus=true#step:4:8).2/x64/bin/bundle' failed with exit code 16

**Comment by mjh2901** [comment]
Fixed sort of, switched to remote theme mode and removed unnecessary folders.  Instructions should list what can be deleted when using remote theme mode.

**Comment by sylhare** [comment]
Hi thanks for opening a PR, would you want to open a PR to contribute to the documentation?

**Comment by sylhare** [comment]
I switched the ruby-setup to use `v1` in the github action, so that should have fixed it.

**Comment by sylhare** [comment]
I have created two different files for the github action to reduce flakiness. Closing this one.
