### ISSUE TITLE
What is the best way to update the repo?

### ISSUE THREAD

**Issue by chefredaktion** [sylhare/Type-on-Strap#363]
Maybe this is a stupid question, but how can I update the theme? Is it the easiest way to compare the changes of the two repos?

**Comment by im-coder-lg** [comment]
Maybe all you need to do is change the gemfile?

**Comment by sylhare** [comment]
if you are using an external theme, you can change the `remote_theme` in your config file, else you would need to copy one theme and paste your posts and assets in the correct folder for each.
