### ISSUE TITLE
how should i localize

### ISSUE THREAD

**Issue by walkingtyphoon** [sylhare/Type-on-Strap#373]
how should i localize

**Comment by sylhare** [comment]
For the blog to work on Github page, we can only use a specific set of gems. And localization was not part of the initial design here. So it's not a supported feature.

However there are some solution, but you may need to pre-build your blog or self host it in order for it to work. Take a look at this PR to enable localization within this theme:
https://github.com/sylhare/Type-on-Strap/pull/284

**Comment by walkingtyphoon** [comment]
Okay, okay, thank you very much for your patient answers and replies, your blog is very good, I hope to see more of your wonderful creations and follow-ups, but at present our current blog cannot fully use markdown for class diagram codes, Looking forward to your follow-up updates, thank you

**Comment by sylhare** [comment]
@walkingtyphoon if you meant changing the english localization, you can do so by updating this file https://github.com/sylhare/Type-on-Strap/blob/master/_data/language.yml 

But you can only have one locale, it does not handle multi-localiztion.

**Comment by walkingtyphoon** [comment]
alright, thank you very much
