### ISSUE TITLE
xml

### ISSUE THREAD

**Issue by walkingtyphoon** [sylhare/Type-on-Strap#374]
The color matching of the xml file code is the same color as the background when it is displayed, hoping to provide solutions and improvements to the template

**Comment by sylhare** [comment]
I see, well it's hard to know which variable you change with your commit messages, did you change the text color variables or the scss files?

By default it works, check: https://sylhare.github.io/Type-on-Strap/2019/11/02/Tech-stuff-example.html

**Comment by sylhare** [comment]
Closing for now

**Comment by walkingtyphoon** [comment]
I changed and submitted the article directly after downloading, or I will try again
