### ISSUE TITLE
How to set the first picture on the blog homepage without limiting the height

### ISSUE THREAD

**Issue by walkingtyphoon** [sylhare/Type-on-Strap#375]
Can I set the first picture on the home page of the blog without any height limit? or where can I set the height

**Comment by sylhare** [comment]
There's no settings for the size of the main image, also the scrolling effect requires a bigger image so if you want a static image of any height you will have to do some adjustment in the js code and the include/blog.scss.

**Comment by walkingtyphoon** [comment]
I just hope he can temporarily take a picture normally, can you teach me

**Comment by walkingtyphoon** [comment]
I just hope he can show photos normally, can you teach me?

**Comment by sylhare** [comment]
For visitor statistic, you would need to use a third party tool like Google Analytics: https://github.com/sylhare/Type-on-Strap#google-analytics

> I just hope he can show photos normally, can you teach me?
I can give you a review, ping me on a PR.

**Comment by walkingtyphoon** [comment]
Can I use email to communicate? if convenient
