### ISSUE TITLE
My class diagram cannot be displayed.

### ISSUE THREAD

**Issue by walkingtyphoon** [sylhare/Type-on-Strap#376]
My class diagram cannot be displayed. I have tried many methods and studied your blog for a long time, but he keeps reporting errors. I am going to crash. Here is my link[blog](https://www.istyphoon.top/java/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/2023/01/10/Adapter.html)

**Comment by sylhare** [comment]
Could be the version of mermaid, I'll update it

**Comment by sylhare** [comment]
The issue is the `<<interface>>` the `<` does not work well in HTML, so you can either try to escape it or use:
```html
  <div class="mermaid" id="1">
  classDiagram
      Print <-- Main:Uses
      Print <|.. PrintBanner
      Banner <|-- PrintBanner
      class Main
      interface Print
        Print: printWeak()
      class PrintBanner{
        printWeak()
        printStrong()
      }
      class Banner {
       showWithParen()
       showWithAster()
      }
  </div>
```

And it should work

**Comment by walkingtyphoon** [comment]
alright, thank you very much
