### ISSUE TITLE
Multi-line header with HTML tags breaks `twitter:description` `meta` tag

### ISSUE THREAD

**Issue by nickchen120235** [sylhare/Type-on-Strap#398]
**Describe the bug**
If `header_text` is set to multi-line content with HTML tags, the content of `twitter:description` `meta` tag will overflow to `body`.

**To Reproduce**
1. Set `header_text` in `_config.yml` to
```yaml
header_text: >
  This is the first line
  <div style="color: white">This is the second line</div>
```
2. Start the jekyll server
3. Observe the overflow

**Expected behavior**
Overflow should not happen

**Screenshots**
![image](https://github.com/sylhare/Type-on-Strap/assets/45678482/71b241c8-9bec-42cc-81db-6a204996115a)

![image](https://github.com/sylhare/Type-on-Strap/assets/45678482/12d7d153-674a-40eb-95ac-23ba0a740857)

**Comment by sylhare** [comment]
Nice thanks, let me check the linked PR ;)
