### ISSUE TITLE
No rss Icon in footer when enabled

### ISSUE THREAD

**Issue by Jeansen** [Sylhare/Type-on-Strap#40]
If I set 
``` 
theme_settings:
     rss: true
```
in `_config.yml` I can see a blue circle for rss, but there is no icon on it.

**Comment by Sylhare** [comment]
Allo,

Are you sure you have the latest version of the template? When I enable the RSS in theme_settings I have it displayed:

![image](https://user-images.githubusercontent.com/20642750/34326870-8f7e53a6-e8b7-11e7-9de7-608608153525.png)

Can you print a screen shot ?

**Comment by Jeansen** [comment]
@Sylhare I hope so!  I have cloned the repo yesterday. Here is what it looks like:
![selection_004](https://user-images.githubusercontent.com/9211499/34327220-277a3c7c-e8bf-11e7-8c4d-e8c225c3f17d.png)

**Comment by Sylhare** [comment]
Hum that's weird, did you do any modifications?
If you have a link to the repo, or if it's hosted online I would be able to see what has happened.

**Comment by Jeansen** [comment]
No, not yet. But I found out: This only happens in Firefox. In google Chrome it is fine!

**Comment by Jeansen** [comment]
OK, must be something in my local setup. Starting Firefox in safe-mode shows no problem.
