### ISSUE TITLE
Author name in posts without author-id and config.yml

### ISSUE THREAD

**Issue by CarlosGrohmann** [sylhare/Type-on-Strap#401]
Is it possible to have an author name show up on posts without using  author-id and having the info in config.yml? I'm working on a site that will be managed by several people, including guest posts, and having to include each one into config.yml would be problematic. Thanks

**Comment by sylhare** [comment]
I think you could, but it might not display an image or a link for the guest.
Did you try using something like that?
```md
---
layout: post
title: Guest Post
author: guest author
---
```

I don't think we have the possibility for a default author image, but that could potentially be added.
