### ISSUE TITLE
Setting post_navigation: true results in syntax error

### ISSUE THREAD

**Issue by Jeansen** [Sylhare/Type-on-Strap#41]
if I set  `post_navigation: true` in `_config.yml`, I get the followin error when starting jekyll:

```
Liquid Exception: Liquid syntax error (/home/projects/test/_includes/post_nav.html line 20): Unknown tag 'endif' included in /_layouts/post.html
```

**Comment by Sylhare** [comment]
Oh true!

I'll fix that right away ;)

**Comment by Sylhare** [comment]
Fixed!

**Comment by Jeansen** [comment]
![selection_007](https://user-images.githubusercontent.com/9211499/34327924-c3fe1584-e8d1-11e7-86aa-4a99efac2f70.png)

Is this supposed to look like this? It looks a bit strange, doesn't it?!

**Comment by Sylhare** [comment]
It was a bit too modern eheh. 
I have changed it, I hope it is better.

![image](https://user-images.githubusercontent.com/20642750/34336780-4e5e867c-e95a-11e7-9607-7e592e2fd287.png)

**Comment by Jeansen** [comment]
Yes, looks better now :)
