### ISSUE TITLE
posts snippets(Markdown) not converted before including in homepage(HTML)

### ISSUE THREAD

**Issue by Pro-Panda** [Sylhare/Type-on-Strap#43]
Posts are written in markdown and their snippet is displayed on home takes it in html. Hence, the contents of the posts aren't properly displayed. 
Eg: [this post](https://sylhare.github.io/Type-on-Strap/2014/11/29/feature-images.html) 
On the homepage, this post looks a bit odd

**Comment by Sylhare** [comment]
Hi,

Are you talking about  ` ``` ` in the post?
Do you have a screenshot showing what you want to achieve?

Thankd

**Comment by Pro-Panda** [comment]
Hi,
Yes `...` as well and the rest of the code isn't formatted in the snippet of the post that's displayed on the homepage.
I have used marked.js to convert markdown to HTML.
i also tried 
```
<section class="post-content">
                {{ post.content | strip_html | truncate: "250" }}
</section>
```
in the HTML page, but ```truncate:"250"``` is causing an issue. It works fine without it, but it returns the entire post.

**Comment by Pro-Panda** [comment]
Could you guide me how to truncate the text ?
Thanks

**Comment by Sylhare** [comment]
Hi,

On the homepage `home.html`, I used `truncate: "250"` to create an excerpt of the article (a little summary of 250 words). I added a `strip_html` to avoid any error.

For the highlight of code, you need to use the liquid tags:
```js
{% highlight js %}

function foo() {}

{% endhighlight %}
```
For example I removed the ` ``` ` that were useless and now it looks like that:
![image](https://user-images.githubusercontent.com/20642750/34463454-bf3b676e-ee5c-11e7-8b1f-0b6acb3c0541.png)

But I still have trouble seeing what you wish to do.

**Comment by Sylhare** [comment]
Hi @Pro-Panda what do you think of the actual? Is it what you wanted to achieve?

**Comment by Pro-Panda** [comment]
I am using a quick hack by using a snippet variable and writing it along with post title and tags, in HTML.

**Comment by Sylhare** [comment]
Ok I think I know what you mean, do you have the markdown of the post in [http://pro-panda.tech](https://www.pro-panda.tech/2017/12/29/2nd-Semester-post.html)?

I have multiple request concerning the code layout, I would need to make some test.

**Comment by Sylhare** [comment]
Well the problem is that I didn't want to get title on the excerpt (the small text in the home page). So I strip off all of the HTML and thus the markdown formating. However it is still rendered correctly in the post.

With that extent I wanted to achieve a more uniform home page (with title, image or not and normal text beneath.)
So to fix your problem, you would need to remove the `strip_html` in the liquid tag. I will see if I can come up with some kind of switch option that could let you display or not formatting (like code formatting) in the excerpt.

**Comment by Pro-Panda** [comment]
> I have multiple request concerning the code layout, I would need to make some test.
Sorry, this message got skipped. Do you want the code ?

> So to fix your problem, you would need to remove the strip_html in the liquid tag.
I tried removing  `strip_html`, but it disturbed the indentation on the post text.

**Comment by Sylhare** [comment]
Well I am ok now, it was to better understand your problem. I will look into how to deal with it.
