### ISSUE TITLE
Comment portfolio on _config.yml "Search broken"

### ISSUE THREAD

**Issue by Vctrsnts** [sylhare/Type-on-Strap#441]
**Describe the bug**
I Work with docker ```bretfisher/jekyll-serve:latest``` with this versions:
- Jekyll: 4.3.3
- Ruby: 3.1.5
- Fork about this theme

**To Reproduce**
1. I fork the theme and go to the ```_config.yml```
2. Comment with this ```#``` the lines about ***portfolio***:
```
#collections:
#  portfolio:
#    output: true
#    permalink: /:collection/:name
```
4. Run the theme and use the search option on firefox 
5. With F12 I watch this message:
```
Uncaught Error: SimpleJekyllSearch --- failed to get JSON (/assets/data/search.liquid) 
a http://192.6.0.40:4001/assets/js/vendor/simple-jekyll-search.min.js:6
SimpleJekyllSearch http://192.6.0.40:4001/assets/js/vendor/simple-jekyll-search.min.js:6
h http://192.6.0.40:4001/assets/js/vendor/simple-jekyll-search.min.js:6
load http://192.6.0.40:4001/assets/js/vendor/simple-jekyll-search.min.js:6
SimpleJekyllSearch http://192.6.0.40:4001/assets/js/vendor/simple-jekyll-search.min.js:6
<anonymous> http://192.6.0.40:4001/search/:35
```
7. If you not comment the lines of ***portfolio*** all work perfect
8. See error

**Expected behavior**

**Screenshots**
![github](https://github.com/sylhare/Type-on-Strap/assets/59069334/1774ce60-2f9e-445a-b5e6-df7e3c28f4d2)

**Additional context**

**Comment by sylhare** [comment]
Ok I see where this is from, the JSON is created by looping through the collections. With no collection the JSON might get broken or the liquid template might be failing.

**Comment by sylhare** [comment]
A fix has been merged 👍
