### ISSUE TITLE
RSS feed is not generated

### ISSUE THREAD

**Issue by schneidr** [Sylhare/Type-on-Strap#48]
The feed.xml file referenced by the theme is not being generated. I tried adding `jekyll-feed` under `plugins` in the `_config.yml` file. This resulted in this error message when starting `jekyll serve`.

>   Dependency Error: Yikes! It looks like you don't have jekyll-feed or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-feed' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/!

Even after running `sudo gem install jekyll-feed` successfully the startup error persists. What do I need to install to get the RSS feed working?

**Comment by Sylhare** [comment]
Let me test that, I am coming back to you asap. I will check the steps on my side (I might have overlooked something)

**Comment by Sylhare** [comment]
Hi,

It was my mistake, I had deleted the feed.xml file that get generated when launching the website. It should be better now.
Tell me if the format is good.

Thanks

**Comment by schneidr** [comment]
Great, thanks.
