### ISSUE TITLE
Page build warning

### ISSUE THREAD

**Issue by misaelljr** [Sylhare/Type-on-Strap#52]
Dear,

I uploaded the project to github pages and am getting the error:

The page build completed successfully, but returned the following warning for the `master` branch:

You are attempting to use a Jekyll theme, "type-on-strap", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

How can I solve this?

**Comment by Sylhare** [comment]
Go to your `_config.yml` and then comment this line:

```yaml
   theme: type-on-strap # If using the theme as a jekyll theme gem
```

That way github won't try to download the gem. (Only a few gems are accepted on github page, this line is when the theme is used with the gem).

**Comment by misaelljr** [comment]
Good, this solved.

Sometimes I have a problem when I update the files. The page opens as if it did not find the .css. What is the cause of this?

**Comment by Sylhare** [comment]
Allo,

I think you should edit your `config.yml` file, make sure to follow the steps in the readme. Seems like you didn't populate the `url` or `base url` with your information (github page url). It's at the beginning.

Let me know if that fixes it.

**Comment by misaelljr** [comment]
It worked correctly. I think it takes a while for github to process changes or update content.

Thanks
Regards
