### ISSUE TITLE
Disqus can not be enable ?

### ISSUE THREAD

**Issue by LiuJQ** [Sylhare/Type-on-Strap#55]
Thanks for this template very much.
I have build my Github Pages blog by using this template, but even I fill in the "disqus_shotname" Disqus can not load.

**Comment by Sylhare** [comment]
Hi, thanks for trying Type On Strap!

Did you try troubleshooting with Discus help page? at [Help Discus: Unable to load disqus](https://help.disqus.com/customer/portal/articles/472007-i-m-receiving-the-message-%22we-were-unable-to-load-disqus-%22)?

If it does not change anything, let me know I will try to help you out ;)

**Comment by Sylhare** [comment]
Well the problem isn't Jekyll or the theme. 

Looks to me you haven't registered a shortname for your site on Disqus yet. If you had, disqus_kumOCV9cJd.discus.com would work and instead it's saying the forum doesn't exist. disqus_kumOCV9cJd is your username and a shortname. (Maybe you should find something easier than that)

Check out this [page](https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-) on Disqus on more info on how to setup one for your site. After you create a shortname for your site then replace your `discus shortname` in your` _config.yml`.

 Disqus should then work properly.

**Comment by LiuJQ** [comment]
Exactly, I follow your instruction and Disqus is working now, thanks so much. ~_~

**Comment by Sylhare** [comment]
Good ;)
