### ISSUE TITLE
ERROR installing Jekyll: Failed to build gem native extension

### ISSUE THREAD

**Issue by judytime** [Sylhare/Type-on-Strap#57]
I am having some difficulty installing jekyll. 
I have version:
```
 gem v2.5.2
 ruby v2.3.3
```

I am trying to run ```sudo gem install jekyll```

The error I am receiving is
```
ERROR:  Error installing jekyll:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20180307-18103-4ueyyk.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/http_parser.rb-0.6.0/gem_make.out
```

I have tried to run the development packages 
```
sudo apt-get install ruby-dev
```
```
sudo yum ruby-devel
```
errors
```
sudo: apt-get: command not found
```
```
sudo: yum: command not found
```

Any help would be appreciated.  Thanks!

**Comment by Sylhare** [comment]
Hi!

Which OS are you using ? 
(I see you've tried both ubuntu and fedora command lines to install the ruby dev tools)

**Comment by judytime** [comment]
Hello!  Thanks for the quick reply.  I have a macOS 10.13.3 (17D102).

**Comment by Sylhare** [comment]
Ok, then it might be that you haven't the xcode commandline tools installed, it's like Apple dev tool box.
You can either download it from the appstore or run:
```
xcode-select --install
```

Let me know if that work.

**Comment by judytime** [comment]
You are amazing, thank you! Sucessfully installed ```jekyll 3.7.3```

**Comment by geoffreyhale** [comment]
I'm having the same problem on Ubuntu 16.04.

**Comment by Sylhare** [comment]
Hi what did you run?

Di you try #1 solutions?

**Comment by geoffreyhale** [comment]
Yes, of course :). The proposed solutions didn't work in my case.

I solved the problem some other way.  Unfortunately, I didn't document the solution or share here and it was a few days ago and I've forgotten already.

Can disregard, thank you.
