### ISSUE TITLE
First page title in navigation displays twice

### ISSUE THREAD

**Issue by Scaranman** [Sylhare/Type-on-Strap#58]
Like, the title implies, the first nav item displays twice. In this case, it's the About page. I've attached a snippit below.
![capture](https://user-images.githubusercontent.com/21231079/37729274-f26d6016-2d12-11e8-97b4-eb5a3cf981a8.PNG)

I've tried it with a brand new jekyll site and it does the same thing.

**Comment by Sylhare** [comment]
Hi! 

It is strange indeed. However, it does not appear to look like the type on strap default theme.
Do you have a link to the code, or can you post a snippet of the html you are using for the navbar?

I have seen this behaviour on another github page, I don't know if it is related.
The demo site seems to be working:
[https://sylhare.github.io/Type-on-Strap/](https://sylhare.github.io/Type-on-Strap/)

**Comment by Scaranman** [comment]
Sorry, I've been running it locally as I'm still working on it. I'll try deploying it to a github page and see if it works.

**Comment by Sylhare** [comment]
Ok, 

So my guess is that you would have two pages called "about" in your repository that's why it appears twice.
But if you upload it at some point and the issue is still there, let me know so I can check it up quickly :wink:

**Comment by Scaranman** [comment]
I just checked, and that was the problem. It might have to do with me downloading the template off of http://jekyllthemes.org/

**Comment by Scaranman** [comment]
Thanks!

**Comment by Sylhare** [comment]
Cool ;)
