### ISSUE TITLE
Limit excerpt

### ISSUE THREAD

**Issue by jmn** [Sylhare/Type-on-Strap#60]
Is there any way to control what goes out as the excerpt to the home page. If not, would it be possible to add a way to limit the length of the excerpt from the post?

For example I have a short post followed by a code block and it looks very strange on the homepage, it would look much better if I could limit the length of the excerpt so it would not include the beginning of the code block.

Thanks for the theme!

**Comment by jmn** [comment]
I used https://jekyllrb.com/docs/posts/#post-excerpts and modified the home page template to use post.excerpt which solved it for me.

**Comment by Sylhare** [comment]
Yes I saw the excerpt thing after, and was planning to work on it.
However if you have something, you can send me a pull request, I would be glad to review it 👍

**Comment by Sylhare** [comment]
Thanks for letting me know, I have made the correction.
I hope it works like yours. If you see anything please feel free to send a pull request or let me know 👍
