### ISSUE TITLE
Line numbers disappear in code blocks

### ISSUE THREAD

**Issue by jmn** [Sylhare/Type-on-Strap#61]
`td.rouge-gutter` has a `width` of 1em, that makes line numbers hidden when I enable them. However changing the width of `td.rouge-gutter` to 3em makes the line numbers display correctly.

Example case: http://www.jmnorlund.net/log/2018/03/notes-program-in-haskell

**Comment by Sylhare** [comment]
Oh, ok thanks I will look into it and correct that 😉

**Comment by Sylhare** [comment]
I put `2em` since you could see the number and the gutter was not to big. But I guess, you would not print too long piece of code at once.
