### ISSUE TITLE
Formatting issue with Jupyter Notebook dataframe rendered through nbconvert 

### ISSUE THREAD

**Issue by jss367** [Sylhare/Type-on-Strap#63]
The theme doesn't work well with dataframes generated by the Python library "pandas". The text in the column headers is squeezed together such that it's hard to read. Here's an example: https://jss367.github.io/blog3/df_test.html

Would it be possible to make the formatting work with these tables? This one, for example, works well with these types of tables: https://github.com/artemsheludko/flexible-jekyll

**Comment by Sylhare** [comment]
Hi!

It seems you are using some kind of converter to create markdown pages that would work with jekyll from a Jupyter Notebook.

I am not familiar with that tool, I guess to make it work you should try to change some of the options. Or try to look at:
https://github.com/Sylhare/Type-on-Strap/blob/master/_posts/2014-08-08-Markup-%20Syntax%20Highlighting.md

For how the markup and syntax coloring work on this theme.

If you can send me more information on what tool you are using, I would be able to troubleshoot with you. 
Thanks

**Comment by jss367** [comment]
Correct, I'm using [nbconvert](https://github.com/jupyter/nbconvert). I'll read up on the link you posted.

**Comment by Sylhare** [comment]
I have done a couple of tests. It seems that the dataframe from the convertion is rendered through a table. And unfortunately this table is way too big to be rendered properly in the length of a normal screen using the default theme css.

So what could be done is to use the `dataframe` keyword to build a custom css to fit your need.
I don't see any dataframe on the link you sent me, but if you have a link how you'd want it to look like. I could help you with it.

**Comment by jss367** [comment]
Here's an example of the same tables I sent you, but using the [flexible jekyll theme](https://github.com/artemsheludko/flexible-jekyll): https://jss367.github.io/blog2/df_test.html
I think this works well for moderately sized tables.

**Comment by Sylhare** [comment]
ok i'm working on a fix

**Comment by Sylhare** [comment]
Should look good now 😉

**Comment by jss367** [comment]
It looks great. Thanks so much!
