### ISSUE TITLE
Can I build a page looks like home and put it on my navigationbar ?

### ISSUE THREAD

**Issue by LiuJQ** [Sylhare/Type-on-Strap#64]
Now I can write article in _post directory and it will display in home page, but I want to write something different and display it in different dir like _post.

Is it possible ?

**Comment by LiuJQ** [comment]
Okay, I found the solution.
Check [this](https://stackoverflow.com/questions/33163141/jekyll-pagination-on-multiple-pages/33179651#33179651) for detail.

Close it, thx.

**Comment by Sylhare** [comment]
Yup collection, I did one for the portfolio.
Perfect ;)
