### ISSUE TITLE
Inline code blocks

### ISSUE THREAD

**Issue by binhonglee** [Sylhare/Type-on-Strap#66]
There doesn't seems to be any configuration done for inline code blocks either on highlighting or fonts.

**Comment by Sylhare** [comment]
Hi,

Take a look at this post: https://sylhare.github.io/Type-on-Strap/2014/08/08/Markup-Syntax-Highlighting.html

And here is the markdown version, so you can start testing the highlighting: https://github.com/Sylhare/Type-on-Strap/blob/master/_posts/2014-08-08-Markup-%20Syntax%20Highlighting.md

If you would like something more, I would be interested to have a visual example of what it could be ;)
Thanks
