### ISSUE TITLE
 How to increase article sidebar, index?

### ISSUE THREAD

**Issue by jicki** [Sylhare/Type-on-Strap#67]
Sorry my English is very bad !

How to add a side index bar in the article,  toc

this    https://github.com/ghiculescu/jekyll-table-of-contents

thank !!

**Comment by Sylhare** [comment]
Well, it is explained on the link. If you want to customize the theme it is up to you.

### Basic Usage
The script requires jQuery. First, reference toc.js in templates where you would like to add the table of content. Then, create an HTML element wherever you want your table of contents to appear:

```html
<div id="toc"></div>
```

Finally, call the .toc() function when the DOM is ready:

```html
<script type="text/javascript">
$(document).ready(function() {
    $('#toc').toc();
});
</script>
```

**Comment by Sylhare** [comment]
Here I have made an example:

https://sylhare.github.io/Type-on-Strap/2017/12/12/toc.js-for-table-of-content.html

 with that, you are all set ;)
