### ISSUE TITLE
Arrows not going to the top of the page on "tags" page

### ISSUE THREAD

**Issue by Sylhare** [Sylhare/Type-on-Strap#7]
It seems the anhor on the tags.html page is not working or that the current URL to go to that anchor is not working `https://sylhare.github.io/Type-on-Strap/tags/#tags`.

I will need to correct that.

**Comment by Sylhare** [comment]
Ok this is basic html in fact ...
The key to create an anchor is to have the field `id` populated with the anchor name, so that your link get you to there.

```html
<a id=anchor href="#anchor">I am an anchor</a>

<a href="#anchor">I am a link to that anchor above</a>
```

Then you mix it with liquid tags and you can optimize your jekyll page!

**Comment by Sylhare** [comment]
This fixed, Will be pushed into master at the next release.

**Comment by arthurlacoste** [comment]
This is not working on your demo, and either in my tests.

**Comment by Sylhare** [comment]
Allo, 

I have tested it on the demo, it brings back to the title of the page when you click on the arrow (on firefox).

- Did you try with the latest version of the project?
- What browser are you using for the demo?

**Comment by arthurlacoste** [comment]
Sorry, I need to open a new issue, it's more about tag page itself (there is one?)

![kapture 2017-11-11 at 0 24 01](https://user-images.githubusercontent.com/13712263/32682747-0479290a-c677-11e7-834c-111efbb8d85a.gif)

Page is link is like this : `http://127.0.0.1:4000/pages/tags/#micodeyt`

I've try in dev  & master branch without success.

**Comment by Sylhare** [comment]
Oh ok I see, nice catch ;)
