### ISSUE TITLE
kramdown   GFM  toc

### ISSUE THREAD

**Issue by jicki** [sylhare/Type-on-Strap#70]
## add _config.yml

```
# BUILD SETTINGS
markdown: kramdown
kramdown:
    input: GFM

```

 ##  the table of content

```
* TOC
{:toc}

```

* How to add toc automatically and add toc to the side  

* Please help me thanks

**Comment by Sylhare** [comment]
Hi, 

I didn't know you could do that with Kramdown. You can try with toc.js as mentionned here:
https://sylhare.github.io/Type-on-Strap/2013/12/12/toc.js-for-table-of-content.html

Else if you find out with kramdown or if you have the link to a theme where it works, let me know.

**Comment by jicki** [comment]
Hi, Sylhare

github link
```
https://github.com/jicki/jicki.github.io/blob/master/_posts/2013-12-12-toc-for-table-of-content.md
```
blog link
```
https://jicki.me/2013/12/12/toc-for-table-of-content.html
```

* Could you please tell me how to make the pos add table of comments automatically. And I need the table of comments  to be displayed in the sidebar instead of at the top of the article.

**Comment by Sylhare** [comment]
Oh, from what I see, it seems that there is a custom css to display the table of content on the side. I would need the actual url to that example in the picture, so I can see how they've done it.

Currently speaking it is not implemented, so you can't see it on the side.

**Comment by jicki** [comment]
## example url
```
https://tianqi.name/jekyll-TeXt-theme/test/2015/01/01/article-with-long-toc.html

```

## github url

> https://github.com/kitian616/jekyll-TeXt-theme

```
https://github.com/kitian616/jekyll-TeXt-theme/blob/master/test/_posts/2015-01-01-article-with-long-toc.md
```

* thank !

**Comment by Sylhare** [comment]
Thanks! I will take a look at it. And see how it can be implemented 😉

**Comment by jicki** [comment]
:) thank !

**Comment by jicki** [comment]
my english so bad ~, the english is to google .

The problem I want to solve is that when I view the article, I can navigate directly to a title through the side navigation bar without having to go back to the article header for navigation.

**Comment by sylhare** [comment]
Hi,

I haven't found a "moving table of content" out of the box. I don't plan on doing one right now. Since there are nothing since July 2018. I am going to close this one, I may reopen it if I find a solution or someone suggest one.

Sorry.
