### ISSUE TITLE
LinkedIn link is not working

### ISSUE THREAD

**Issue by azmirfakkri** [Sylhare/Type-on-Strap#71]
Thanks for the great theme! 

I have followed the documentation regarding links to other platforms like github etc, however, when I click on my LinkedIn icon it brings me to 404 Page Not Found. I have copied and pasted the whole url for linkedin on _config.yml as written in your documentation.

**Comment by Sylhare** [comment]
Allo,

The 404 is from the linkedin side, meaning they can't find your profile using the url provided. 
Are you sure it is the right linkedin address? Try to go from linkedin on your profile then copy and paste again your profile url in the `_config.yml`.

**Comment by azmirfakkri** [comment]
It is a correct link but does not seem to work. I

**Comment by azmirfakkri** [comment]
The link is now working but I had to change my original LinkedIn link.
