### ISSUE TITLE
special page's link is always search

### ISSUE THREAD

**Issue by yshrsmz** [Sylhare/Type-on-Strap#72]
https://github.com/Sylhare/Type-on-Strap/blob/e48394f91154f994857b54a3b7892940eb6abee9/_includes/navbar.html#L48

here.
also, looks like `enabled` property has no effect 🤔

**Comment by Sylhare** [comment]
True, thanks I need to correct that

**Comment by Sylhare** [comment]
Corrected:
 - The links are setted to the correct page
 - Enabled when false truly remove the pages from the navbar.
