### ISSUE TITLE
Remove JQuery

### ISSUE THREAD

**Issue by mathieubrun** [Sylhare/Type-on-Strap#74]
FIrst, thanks for the great theme !

JQuery does not seem to be required, removing it may shave a few KB and improve page load speed :)

I had it working on my site here : https://github.com/mathieubrun/mathieubrun.github.io

If you want I can fork and make a PR ?

**Comment by Sylhare** [comment]
Hi

Actually JQuery is used for the gallery page, the portfolio page and also to make the image in the post header to move as it is scrolled.

It could be possible to add a condition but I don't think that's worth the change. I can see issue coming with people having pages not working because JQuery was not put 'on'.

**Comment by Sylhare** [comment]
Yeah, I had something like that in mind, a flag for everything to be loaded locally (every vendor scripts if enabled) and a flag for everything loaded from the CDN. That could be a good feature 👍

**Comment by mathieubrun** [comment]
@Sylhare yes it's small compared to the images (I'm having a look at those at the moment), but I wanted to see if I could remove it ;)

I did not see the gallery dependency on jquery when I did it locally.

**Comment by Sylhare** [comment]
@mathieubrun, true the masonry library seems not to need JQuery to work, however I used JQuery to initialize it. Probably by converting all of the JQuery to vanilla javascript you would kill the JQuery dependancy apart from the bootstrap portfolio. 

That could be an even better solution 🤔 wouldn't it?

**Comment by mathieubrun** [comment]
@Sylhare yes this could be done. I had the snippet for the scrolling and the css. Regarding the portfolio, it looks like you're not using any bootstrap component that is using JS. The bootstrap js could be removed then. Also, you could switch to flexbox layout ( https://caniuse.com/#feat=flexbox ) and ditch bootstrap as well ?

**Comment by Sylhare** [comment]
Yup, I was thinking toward making that move. I am going to create an issue for each of them.
If you want to help on some, let me know. 😉It is greatly appreciated!

**Comment by mathieubrun** [comment]
Done on my fork, just need to do some checks with IE !

**Comment by Sylhare** [comment]
Amazing! I will review the PR once you are ready 😁 
It feels like JQuery might soon be gone from the theme after all!

**Comment by Sylhare** [comment]
JQuery is now removed from the theme 🎉  
Big thanks to @mathieubrun !
