### ISSUE TITLE
Separate search json and JS in separate files

### ISSUE THREAD

**Issue by mathieubrun** [Sylhare/Type-on-Strap#75]
Search json can be put in a separate file and loaded asynchronously. This will reduce search page size and loading time.

I had it working on my site here : https://github.com/mathieubrun/mathieubrun.github.io

I can make a PR if requested !

**Comment by Sylhare** [comment]
Yeah, it was like that at first the only issue is that as a gem the search feature does not work. So I put everything in one file as a workaround. 
If you can make it work on a separate file while being on a gem, I would be good with it. 👍

**Comment by mathieubrun** [comment]
I'll have a look if I can make it working then !

**Comment by mathieubrun** [comment]
PR here https://github.com/Sylhare/Type-on-Strap/pull/78

**Comment by Sylhare** [comment]
Thanks! I have merged it 😉
