### ISSUE TITLE
How can I remove the suffix("username.github.io")  of page title for each page ?

### ISSUE THREAD

**Issue by LiuJQ** [Sylhare/Type-on-Strap#76]
Well, I try to change the include file "head.html" aim to modify title for each page, like this:
```html
<title>{% if page.title %}{{ page.title }}{% else %}{{ site.theme_settings.title }}{% endif %}</title>
```
but there's always suffix which is "username.github.io" in title, help pls.

**Comment by Sylhare** [comment]
Hi, 

Can you give an example of what you would like to have as a title for both case (if the page has a title or not).
And what it looks like when you do it (you can drag and drop screenshot here so I can see it).

Thanks

**Comment by LiuJQ** [comment]
okay, now the title is like this blow
> Jackin's blog | LiuJQ.Github.io

and, I just want to remove "| LiuJQ.Github.io", but whatever I do, it is always there, so sad.

**Comment by Sylhare** [comment]
I am trying to replicate the issue, but on my side I don't see it.

You mean as a title of the page? In the navigation bar?
I try more to see where is your problem, if you have more information, that would help me.

**Comment by LiuJQ** [comment]
Yeah, I mean the title of the page, here is the screenshot:
![ladpbbcc1bbbtmlnafhnbaa_1440_497](https://user-images.githubusercontent.com/3191942/39736248-b601a190-52b1-11e8-9408-ea2ce0f2a68f.jpg)

**Comment by LiuJQ** [comment]
The culprit is the jekyll-seo-tag plugin, it will replace all the page title for your posts and pages, if you just use it like this:
```html
{% seo %}
```

I found the advance usage guide for Jekyll-seo-tag plugin, and we can disable the title output:
```html
{% seo title=false %}
```

**Now the problem can be solved.**
