### ISSUE TITLE
Social media share buttons

### ISSUE THREAD

**Issue by azmirfakkri** [Sylhare/Type-on-Strap#77]
This is an enhancement suggestion, adding social media share buttons for posts. 
Thank you!

**Comment by Sylhare** [comment]
Yeah sounds like a good stuff, I will look at how it can be done. I think it is mostly a snippet from the popular network to add at the end of the page.

**Comment by CookiePLMonster** [comment]
Indeed, a snippet will suffice! Even though technically I'm a total noob when it comes to any web dev, adding those to template of my blog basing on your theme (awesome work, by the way! I love how customizable and easy to tinker with it is) proved to be trivial:

https://github.com/CookiePLMonster/CookiePLMonster.github.io/blob/master/_includes/share-post.html
https://github.com/CookiePLMonster/CookiePLMonster.github.io/blob/master/_layouts/post.html

**Comment by Sylhare** [comment]
Nice stuff! Wanna make a PR for those icons?

**Comment by CookiePLMonster** [comment]
Sure! I hardcoded the ones I was interested in, but I presume the best way will be to expose toggles for each share option in the config file.

FYI I didn't come up with those on my own - I used this page:
https://simplesharingbuttons.com/

And the only did minor fixups to the style and FA tags to fit the current style better.

**Comment by Sylhare** [comment]
Oh that's a good tool for creating share icons.  I liked the layout of the icons you used. 
Yeah I was thinking of using the `_config.yml` to flag the share buttons you want to add if any, a bit like in the footer page.

**Comment by CookiePLMonster** [comment]
So my suggestion would be to use this to export **all** supported share options and then expose them to _config.yml separately + maybe a global toggle for the entire bar, like discussions do.

I can issue a PR with it or you can go ahead and commit it, doesn't really make a difference for me.

**Comment by CookiePLMonster** [comment]
Cool! Should have enough time around Tuesday, or sooner.

**Comment by CookiePLMonster** [comment]
Not as fast as I have promised, but my proposal for the implementation is now posted under #83.

**Comment by Sylhare** [comment]
Thanks! I love the icons, it looks superb! 😉
