### ISSUE TITLE
.html post versus .md post

### ISSUE THREAD

**Issue by azmirfakkri** [Sylhare/Type-on-Strap#82]
Hello, 

I created a post using Rmarkdown and put the markdown file in the _post folder, with the correct date format. When Jekyll generate the post, it looks something like this. 

![screen shot 2018-05-16 at 22 40 06](https://user-images.githubusercontent.com/33866698/40145531-2b95e14c-595a-11e8-9e6d-2ef7b078cf04.png)

First question, is the highlighting for codes in the post related to the styles set in this theme?

This is the same blog post but as a .html file, I did not set front matter for this .html file but save it with the correct date format and it looks like this.

![screen shot 2018-05-16 at 22 43 05](https://user-images.githubusercontent.com/33866698/40145631-8da8efbe-595a-11e8-85ea-44b3062354dc.png)

I would like the post to look like the .html file above, however, the Disqus section and footer disappeared altogether. 
So that brings me to my second question, is there a way to handle a .html file in _post folder so that it will also show the Disqus section and footer without changing the style of the post (if that makes any sense to you)?

The repo is here for you to checkout https://github.com/azmirfakkri/azmirfakkri.github.io 

Thanks and appreciate your feedback!

**Comment by Sylhare** [comment]
Hi!
Why don't you put the html inside of a .md post, it should work fine.
Try it out and let me know

**Comment by azmirfakkri** [comment]
Hello, 

This is what I have attempted to put the html inside the markdown, it's very close to what I want it to look like but the toc on the side seems to float all the way down and is being covered some parts of the main content. 

Link to updated post: https://azmirfakkri.github.io/2018/05/16/Data_Science_with_R_Pt_1.html
Link to code: https://github.com/azmirfakkri/azmirfakkri.github.io/blob/master/_posts/2018-05-16-Data_Science_with_R_Pt_1.md

**Comment by Sylhare** [comment]
Hum then you might want to use something like a custom layout. 
Because the page layout has some padding which does not allow your toc to float where you want it to.

**Comment by Sylhare** [comment]
@azmirfakkri 

Here just create a layout call `custom.html` in `_layouts` with that inside:

```
---
layout: default
---
<header id="main" style="background-image: url('{{ site.baseurl }}/{{ page.feature-img }}')">
    <h1 id="{{ page.title | cgi_escape }}" class="title">{{ page.title }}</h1>
    <p class="meta">
    {{ page.date | date: "%B %-d, %Y" }}
    {% if page.author %} - {{ page.author }}{% endif %}
    </p>
  </header>

{{ content }}

<!-- Disqus -->
{% if site.theme_settings.disqus_shortname %}
<div class="comments">
  {% include disqus.html %}
</div>
{% endif %}

<!-- Post navigation -->
{% if site.theme_settings.post_navigation %}
  {% include post_nav.html %}
{% endif %}
```

It's basically the layout for page without the formatting for the `{{ content }}` so you might have more luck for your `.html`.

Then to use is just use
```
---
layout: custom
---
```
then past all of your html

**Comment by azmirfakkri** [comment]
Hey Sylhare, 

Thanks a lot! The post is looking much better. 
Based on your post.html, I have copied the tags part into custom.html. 

Two questions:
1. How do I center the title of the post in the article?
<img width="1514" alt="screen shot 2018-05-18 at 09 07 12" src="https://user-images.githubusercontent.com/33866698/40223446-fd41f278-5a7a-11e8-80eb-8e196d18d44f.png">

2.  How do I limit the vertical limit of the floating table of content so that it doesn't scroll pass the main content?
<img width="1513" alt="screen shot 2018-05-18 at 09 07 31" src="https://user-images.githubusercontent.com/33866698/40223454-0458889c-5a7b-11e8-913c-fbb91c5d3077.png">

Is it somewhere here in the html of the article that I need to play with?
<img width="818" alt="screen shot 2018-05-18 at 09 09 16" src="https://user-images.githubusercontent.com/33866698/40223502-326542c0-5a7b-11e8-985d-d4a5095879c8.png">


Thank you and appreciate your help!

Link to updated post using custom layout: https://azmirfakkri.github.io/2018/05/18/Data-Science-Pt-1.html

**Comment by azmirfakkri** [comment]
Found a quick fix to center the title and date. By adding `style="text-align:center"`.
<img width="1516" alt="screen shot 2018-05-18 at 11 18 48" src="https://user-images.githubusercontent.com/33866698/40229820-51b4fa96-5a8d-11e8-9068-b86695fa9dfb.png">

**Comment by Sylhare** [comment]
Yeah, since it's the default one, you lose pretty much of all the post css that helped put things in place.
I was maybe too optimistic.

Since you are incorporating a whole html, there are some things that are a bit messy.
Unless you know css, you're going to mess up with the theme. And if you need to do it manually, it defeats the purpose :disappointed: 

I think, I might create some html layout for this usecase in order to fix the major bugs you talked about. Like a lightweight post layout to dumb html in. I will let you know if I succeed :wink:

**Comment by Sylhare** [comment]
So I have looked it up and created a more custom way to have a 'post' under the custom layout.

However, the 'toc' can't be controlled because the script is from the html page you have inserted, and the navbar gets tiny and messy because of the css inside the page.
I guess that's as far as I wish to go for now.

Hope it's still ok for you.
