### ISSUE TITLE
Feature image wraps around on mobile

### ISSUE THREAD

**Issue by CookiePLMonster** [sylhare/Type-on-Strap#85]
Just like the title states - feature images for blog posts can wrap if viewed on mobile:

![image](https://user-images.githubusercontent.com/7947461/40254425-b435ce24-5ae3-11e8-9b19-fa926c7be9f9.png)

Is there a way to clamp them instead, so they stop scrolling when they reach the edges?

**Comment by Sylhare** [comment]
Yeah that's a tough issue this one, it mostly depends on the image size. 
It would need some more javascript for it. As of now it is done via CSS.

**Comment by CookiePLMonster** [comment]
I see... I didn't even know you can do this without JS!

**Comment by Sylhare** [comment]
Yes whenever the image is not large enough on small scale it will do that (for example if you reduce the size of your browser it should happen).

Background-repeat will do as in the picture according to me, unless I misunderstood what you wanted to do with it? (or you meant to stop the background repeat?)

**Comment by ColbyEcology** [comment]
@Sylhare Re: "Yes whenever the image is not large enough on small scale it will do that (for example if you reduce the size of your browser it should happen)."

Looking through the documentation, I didn't see an ideal/recommended image size or proportions for the features. Do they exist? Thank you.

**Comment by Sylhare** [comment]
Ah True, I haven't documented that part, I will do that asap ;)

**Comment by ritajitk** [comment]
Is there any way to enlarge the avatar picture a little bit. 
Don't know if this is the right place to ask.

**Comment by sylhare** [comment]
Hi @ritajitk for the avatar picture, you can open a new issue.
