### ISSUE TITLE
How to adjust the home page feature image to middle alignment instead of top alignment.

### ISSUE THREAD

**Issue by EverettYou** [Sylhare/Type-on-Strap#86]
Current the feature image is roughly top aligned. I will like to middle align image. So I tried
`<div id="main" class="call-out"
  style="background-image: url('{{ site.baseurl }}/{{ site.theme_settings.header_text_feature_image }}')" 
  align="middle">`
it does not work out.

**Comment by Sylhare** [comment]
It was intended so you see the image move when you scroll down.
If you really want to see the middle of your image and not the top, then you may try to crop and remove the top part you don't want to see.

**Comment by EverettYou** [comment]
Thanks. Can you tell me in which file and where is this behavior being defined? I do not wish to crop the image because on a mobile device, the image will then not long enough to span the background.

**Comment by Sylhare** [comment]
Hi!

The `.call-out` is defined via css in `_sass/layouts/_index.scss`. 

If you want, for stopping the scrolling, you would need to update the js file `main.min.js` in the assets and remove the scrolling down part. (the file is generated from the other js file, you can just copy them into it beside the scroll down one.)

Let me know if that works for you ;)
