### ISSUE TITLE
We found a potential security vulnerability in one of your dependencies. ?

### ISSUE THREAD

**Issue by jicki** [Sylhare/Type-on-Strap#89]
We found a potential security vulnerability in one of your dependencies.
A dependency defined in package-lock.json has known security vulnerabilities and should be updated.

Only the owner of this repository can see this message.
Learn more about vulnerability alerts

These dependencies are defined in jicki.github.io’s manifest files, such as package-lock.json, package.json, and type-on-strap.gemspec.

```
url 

https://github.com/jicki/jicki.github.io/network/dependencies

```

**Comment by Sylhare** [comment]
Hi!

Yes it seems the vulnerability is on the gulp task that I have added, hence it is not link to the theme. I will see which is faulty is try to replace it.

**Comment by Sylhare** [comment]
Should be good now, I'll keep an eye on it
