### ISSUE TITLE
How to determine which line of post to be in thumbnail?

### ISSUE THREAD

**Issue by ramosjanoah** [Sylhare/Type-on-Strap#93]

**Comment by ramosjanoah** [comment]
I've been searching in config and the post, but it's still give a full text on the pagination page. How to set which line to be in thumbnail?

**Comment by Sylhare** [comment]
Hi, in the readme, I guess you are talking about excerpt.

### Post excerpt

The [excerpt](https://jekyllrb.com/docs/posts/#post-excerpts) are the first lines of an article that is display on the blog page. The length of the excerpt has a default of around `250` characters and can be manually set in the post using:
```yml
---
layout: post
title: Sample Page
excerpt_separator: <!--more-->
---

some text in the excerpt
<!--more-->
... rest of the text not shown in the excerpt ...
```

The html is stripped out of the excerpt so it only display text.
