### ISSUE TITLE
Simplify Bootstrap usage

### ISSUE THREAD

**Issue by CookiePLMonster** [Sylhare/Type-on-Strap#94]
Once again, I felt like I needed access to Bootstrap buttons, but this time I needed them in a post and not a page. To do this, something came to my mind - why would we need a separate layout for Bootstrap? Could just be a toggle in page/post Front Matter.

I have adapted it to my blog and it seems to work wonders:
https://github.com/CookiePLMonster/CookiePLMonster.github.io/commit/cec93d3d8442298d8eb416ad2696bba7c5a4e378

Do you think tweaking it to be like this is feasible? Seems like it would make using Bootstrap more straightforward, without it "leaking" into the theme needlessly (since you seem to want to avoid that).

**Comment by Sylhare** [comment]
Yeah it's sweet!!
I was actually thinking of doing something like that but did not have bandwidth to start it. 
If you want to make a pull request, I would be able to test it a bit. 😄

**Comment by Sylhare** [comment]
PR accepted, I am closing this one ;)
