### ISSUE TITLE
Liquid Exception when using more than one page worth of posts

### ISSUE THREAD

**Issue by m-ender** [Sylhare/Type-on-Strap#96]
I'm just getting started with Jekyll, so I don't know if this is a problem with Jekyll, your theme or just me doing something wrong. When I have more posts than the `paginate:` setting in `_config.yml`, I get an error during `jekyll build`:

    Liquid Exception: no implicit conversion of nil into String in /_layouts/default.html

Since the theme comes with 5 example posts and `paginate: 5`, all I did was add one more post (literally just copying one of the existing samples and giving it a new file name) to result in this error. If I then increase `paginate` to 6, the error goes away and everything works fine.

Any clue what's going on here or how I could diagnose the problem in more detail?

**Comment by Sylhare** [comment]
That is weird indeed. The number in paginate means after which number of posts it goes to page 2. I'll see what's up.
Do you have the repo online? 

Did you change the name both of the file and the title inside the file when adding a new post?
You can troubleshoot using:
```
jekyll build --watch
```
And then adding posts, changing stuff to see what is causing the error.

**Comment by Sylhare** [comment]
@m-ender do you have any update?

**Comment by m-ender** [comment]
Ah sorry, completely forgot about this. I ended up switching to a different theme because I needed to get something up and running quickly. I don't really have time to try and reproduce it now, so feel free to close this issue.

**Comment by Sylhare** [comment]
Ok no problem, I couldn't replicate the issue, so I am closing this one :wink:
