### ISSUE TITLE
Multi-word tags don't work

### ISSUE THREAD

**Issue by jss367** [Sylhare/Type-on-Strap#97]
If I click on a tag when I'm on the tag page it only jumps down to that section if the tags is a single word. For example, when I click on the Natural language processing tag, it doesn't jump down to that section: https://jss367.github.io/tags/#Natural%20language%20processing

**Comment by Sylhare** [comment]
Yup I see the problem, I will correct that asap :wink:
Thanks for reporting

**Comment by Sylhare** [comment]
@jss367 
This was linked to #101 it should be solved now.

**Comment by jss367** [comment]
Awesome. Thanks!
