### ISSUE TITLE
Page tags concatenated on the tags page

### ISSUE THREAD

**Issue by Laogeodritt** [Sylhare/Type-on-Strap#98]
There's a bug in `_layouts/tags.html` causing tags on a page to be concatenated instead of listed separately on the tags page:

```
<!-- cycles through pages to get tags -->
{% for page in site.pages %}
{% assign page_tags = page.tags | join:'|' %}
{% assign rawtags = rawtags | append:page_tags %}
{% endfor %}
```

For example, if you have:

* A page with "about" and "archive" tags
* Another page with an "archive" tag

Then you'd get "about" and "archivearchive" tags listing on the tags page.

Proposed solution:

```
<!-- cycles through pages to get tags -->
{% for page in site.pages %}
{% if page.tags %}
{% assign page_tags = page.tags | join:'|' | append:'|' %}
{% assign rawtags = rawtags | append:page_tags %}
{% endif %}
{% endfor %}    
```

(this if guard is needed for pages that have no tags, to avoid generating an "empty tag" in the tags list - may be useful for posts as well - I haven't tested this but it looks like if any posts have no tags, you'd get an empty tag on this page too)

**Comment by Sylhare** [comment]
Good catch, I think it is linked to single tag array. I'm on it :wink:
